#pragma once

#include <Retina/Core/Forwards.hpp>
#include <Retina/Core/Types.hpp>
#include <Retina/Core/Macros.hpp>

#include <vulkan/vulkan.h>
#include <vulkan/vk_enum_string_helper.h>

#include <type_traits>
#include <array>

namespace Retina {
    namespace Detail {
        #define RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(E, T)             \
            template <> struct SNativeEnumCounterpart<E> { using Type = T; };   \
            template <> struct SNativeEnumCounterpart<T> { using Type = E; }

        template <typename T>
        struct SNativeEnumCounterpart;

        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkImageLayout, EImageLayout);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkObjectType, ENativeObjectType);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkFormat, EResourceFormat);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkQueryType, EQueryType);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkComponentSwizzle, EComponentSwizzle);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkBlendFactor, EBlendFactor);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkBlendOp, EBlendOperator);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkCompareOp, ECompareOperator);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkDynamicState, EDynamicState);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkFrontFace, EFrontFace);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkPolygonMode, EPolygonMode);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkStencilOp, EStencilOperator);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkLogicOp, ELogicOperator);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkBorderColor, ESamplerBorderColor);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkFilter, ESamplerFilter);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkSamplerAddressMode, ESamplerAddressMode);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkSamplerMipmapMode, ESamplerMipmapMode);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkDescriptorType, EDescriptorType);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkAttachmentLoadOp, EAttachmentLoadOperator);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkAttachmentStoreOp, EAttachmentStoreOperator);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkImageAspectFlagBits, EImageAspect);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkImageCreateFlagBits, EImageCreateFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkSampleCountFlagBits, ESampleCount);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkImageUsageFlagBits, EImageUsage);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkMemoryPropertyFlagBits, EMemoryProperty);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkQueryPipelineStatisticFlagBits, EQueryPipelineStatistic);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkQueryResultFlagBits, EQueryResultFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkBufferCreateFlagBits, EBufferCreateFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkColorComponentFlagBits, EColorComponent);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkShaderStageFlagBits, EShaderStage);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkCullModeFlagBits, ECullMode);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkDescriptorPoolCreateFlagBits, EDescriptorPoolCreateFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkDescriptorSetLayoutCreateFlagBits, EDescriptorLayoutCreateFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkCommandPoolCreateFlagBits, ECommandPoolCreateFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkSamplerReductionMode, ESamplerReductionMode);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkDescriptorBindingFlagBits, EDescriptorBindingFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkPresentModeKHR, EPresentMode);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkColorSpaceKHR, EColorSpace);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkAccelerationStructureTypeKHR, EAccelerationStructureType);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkCopyAccelerationStructureModeKHR, EAccelerationStructureCopyMode);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkGeometryFlagBitsKHR, EAccelerationStructureGeometryFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkGeometryInstanceFlagBitsKHR, EAccelerationStructureGeometryInstanceFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkBuildAccelerationStructureFlagBitsKHR, EAccelerationStructureBuildFlag);
        RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION(VkBuildAccelerationStructureModeKHR, EAccelerationStructureBuildMode);

        #undef RETINA_NATIVE_ENUM_COUNTERPART_SPECIALIZATION

        template <typename T>
        using NativeEnumCounterpartType = typename SNativeEnumCounterpart<T>::Type;
    }

    template <typename E>
    constexpr auto ToEnumCounterpart(E e) noexcept -> Detail::NativeEnumCounterpartType<E> {
        return static_cast<Detail::NativeEnumCounterpartType<E>>(e);
    }

    constexpr auto ToEnumCounterpart(EPipelineStage e) noexcept -> VkPipelineStageFlagBits2 {
        return static_cast<VkPipelineStageFlagBits2>(e);
    }

    constexpr auto ToEnumCounterpart(EResourceAccess e) noexcept -> VkAccessFlagBits2 {
        return static_cast<VkAccessFlagBits2>(e);
    }
    
    #define RETINA_ENUM_TO_STRING_OVERLOAD(E, T)                \
        constexpr auto ToString(T e) noexcept -> std::string {  \
            return RETINA_CONCAT(string_, E)(e);                \
        }

    #define RETINA_ENUM_TO_STRING_CONVERSION_OVERLOAD(E, T)         \
        constexpr auto ToString(T e) noexcept -> std::string {      \
            return RETINA_CONCAT(string_, E)(ToEnumCounterpart(e)); \
        }

    #define RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(E, T)    \
        constexpr auto ToString(T e) noexcept -> std::string {          \
            return RETINA_CONCAT(string_, E)(ToEnumCounterpart(e));     \
        }                                                               \
                                                                        \
        constexpr auto ToString(E e) noexcept -> std::string {          \
            return RETINA_CONCAT(string_, E)(e);                        \
        }

    #define RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(F, T, E) \
        RETINA_ENUM_TO_STRING_CONVERSION_OVERLOAD(E, T)       \
        RETINA_ENUM_TO_STRING_OVERLOAD(E, F)

    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkImageLayout, EImageLayout);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkObjectType, ENativeObjectType);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkFormat, EResourceFormat);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkComponentSwizzle, EComponentSwizzle);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkBlendFactor, EBlendFactor);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkBlendOp, EBlendOperator);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkCompareOp, ECompareOperator);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkDynamicState, EDynamicState);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkFrontFace, EFrontFace);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkPolygonMode, EPolygonMode);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkStencilOp, EStencilOperator);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkLogicOp, ELogicOperator);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkBorderColor, ESamplerBorderColor);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkFilter, ESamplerFilter);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkSamplerAddressMode, ESamplerAddressMode);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkSamplerMipmapMode, ESamplerMipmapMode);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkDescriptorType, EDescriptorType);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkAttachmentLoadOp, EAttachmentLoadOperator);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkAttachmentStoreOp, EAttachmentStoreOperator);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkSamplerReductionMode, ESamplerReductionMode);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkPresentModeKHR, EPresentMode);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkColorSpaceKHR, EColorSpace);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkAccelerationStructureTypeKHR, EAccelerationStructureType);
    RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD(VkCopyAccelerationStructureModeKHR, EAccelerationStructureCopyMode);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkImageAspectFlagBits, EImageAspect, VkImageAspectFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkImageCreateFlagBits, EImageCreateFlag, VkImageCreateFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkSampleCountFlagBits, ESampleCount, VkSampleCountFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkImageUsageFlagBits, EImageUsage, VkImageUsageFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkMemoryPropertyFlagBits, EMemoryProperty, VkMemoryPropertyFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkQueryPipelineStatisticFlagBits, EQueryPipelineStatistic, VkQueryPipelineStatisticFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkQueryResultFlagBits, EQueryResultFlag, VkQueryResultFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkBufferCreateFlagBits, EBufferCreateFlag, VkBufferCreateFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkColorComponentFlagBits, EColorComponent, VkColorComponentFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkShaderStageFlagBits, EShaderStage, VkShaderStageFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkCullModeFlagBits, ECullMode, VkCullModeFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkDescriptorPoolCreateFlags, EDescriptorPoolCreateFlag, VkDescriptorPoolCreateFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkDescriptorSetLayoutCreateFlagBits, EDescriptorLayoutCreateFlag, VkDescriptorSetLayoutCreateFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkCommandPoolCreateFlagBits, ECommandPoolCreateFlag, VkCommandPoolCreateFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkDescriptorBindingFlagBits, EDescriptorBindingFlag, VkDescriptorBindingFlags);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkGeometryFlagBitsKHR, EAccelerationStructureGeometryFlag, VkGeometryFlagsKHR);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkGeometryInstanceFlagBitsKHR, EAccelerationStructureGeometryInstanceFlag, VkGeometryInstanceFlagsKHR);
    RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD(VkBuildAccelerationStructureFlagBitsKHR, EAccelerationStructureBuildFlag, VkBuildAccelerationStructureFlagsKHR);

    RETINA_ENUM_TO_STRING_CONVERSION_OVERLOAD(VkPipelineStageFlags2, EPipelineStage);
    RETINA_ENUM_TO_STRING_CONVERSION_OVERLOAD(VkAccessFlags2, EResourceAccess);

    #undef RETINA_ENUM_TO_STRING_OVERLOAD
    #undef RETINA_ENUM_TO_STRING_CONVERSION_OVERLOAD
    #undef RETINA_ENUM_TO_STRING_BASE_AND_CONVERSION_OVERLOAD
    #undef RETINA_FLAG_BITS_ENUM_TO_STRING_OVERLOAD

    // VkImageLayout
    enum class EImageLayout : uint32 {
        E_UNDEFINED = VK_IMAGE_LAYOUT_UNDEFINED,
        E_GENERAL = VK_IMAGE_LAYOUT_GENERAL,
        E_COLOR_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
        E_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL,
        E_DEPTH_STENCIL_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL,
        E_SHADER_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
        E_TRANSFER_SRC_OPTIMAL = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
        E_TRANSFER_DST_OPTIMAL = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
        E_PREINITIALIZED = VK_IMAGE_LAYOUT_PREINITIALIZED,
        E_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
        E_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
        E_DEPTH_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL,
        E_DEPTH_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL,
        E_STENCIL_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL,
        E_STENCIL_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL,
        E_READ_ONLY_OPTIMAL = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL,
        E_ATTACHMENT_OPTIMAL = VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL,
        E_PRESENT_SRC_KHR = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
        E_VIDEO_DECODE_DST_KHR = VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR,
        E_VIDEO_DECODE_SRC_KHR = VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR,
        E_VIDEO_DECODE_DPB_KHR = VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR,
        E_SHARED_PRESENT_KHR = VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR,
        E_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT = VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT,
        E_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR,
        E_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT = VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT,
        E_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR,
        E_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR,
        E_SHADING_RATE_OPTIMAL_NV = VK_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV,
        E_DEPTH_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR,
        E_DEPTH_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR,
        E_STENCIL_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR,
        E_STENCIL_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR,
        E_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR,
        E_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR,
    };

    // VkObjectType
    enum class ENativeObjectType : uint32 {
        E_UNKNOWN = VK_OBJECT_TYPE_UNKNOWN,
        E_INSTANCE = VK_OBJECT_TYPE_INSTANCE,
        E_PHYSICAL_DEVICE = VK_OBJECT_TYPE_PHYSICAL_DEVICE,
        E_DEVICE = VK_OBJECT_TYPE_DEVICE,
        E_QUEUE = VK_OBJECT_TYPE_QUEUE,
        E_SEMAPHORE = VK_OBJECT_TYPE_SEMAPHORE,
        E_COMMAND_BUFFER = VK_OBJECT_TYPE_COMMAND_BUFFER,
        E_FENCE = VK_OBJECT_TYPE_FENCE,
        E_DEVICE_MEMORY = VK_OBJECT_TYPE_DEVICE_MEMORY,
        E_BUFFER = VK_OBJECT_TYPE_BUFFER,
        E_IMAGE = VK_OBJECT_TYPE_IMAGE,
        E_EVENT = VK_OBJECT_TYPE_EVENT,
        E_QUERY_POOL = VK_OBJECT_TYPE_QUERY_POOL,
        E_BUFFER_VIEW = VK_OBJECT_TYPE_BUFFER_VIEW,
        E_IMAGE_VIEW = VK_OBJECT_TYPE_IMAGE_VIEW,
        E_SHADER_MODULE = VK_OBJECT_TYPE_SHADER_MODULE,
        E_PIPELINE_CACHE = VK_OBJECT_TYPE_PIPELINE_CACHE,
        E_PIPELINE_LAYOUT = VK_OBJECT_TYPE_PIPELINE_LAYOUT,
        E_RENDER_PASS = VK_OBJECT_TYPE_RENDER_PASS,
        E_PIPELINE = VK_OBJECT_TYPE_PIPELINE,
        E_DESCRIPTOR_SET_LAYOUT = VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT,
        E_SAMPLER = VK_OBJECT_TYPE_SAMPLER,
        E_DESCRIPTOR_POOL = VK_OBJECT_TYPE_DESCRIPTOR_POOL,
        E_DESCRIPTOR_SET = VK_OBJECT_TYPE_DESCRIPTOR_SET,
        E_FRAMEBUFFER = VK_OBJECT_TYPE_FRAMEBUFFER,
        E_COMMAND_POOL = VK_OBJECT_TYPE_COMMAND_POOL,
        E_SAMPLER_YCBCR_CONVERSION = VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION,
        E_DESCRIPTOR_UPDATE_TEMPLATE = VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE,
        E_PRIVATE_DATA_SLOT = VK_OBJECT_TYPE_PRIVATE_DATA_SLOT,
        E_SURFACE_KHR = VK_OBJECT_TYPE_SURFACE_KHR,
        E_SWAPCHAIN_KHR = VK_OBJECT_TYPE_SWAPCHAIN_KHR,
        E_DISPLAY_KHR = VK_OBJECT_TYPE_DISPLAY_KHR,
        E_DISPLAY_MODE_KHR = VK_OBJECT_TYPE_DISPLAY_MODE_KHR,
        E_DEBUG_REPORT_CALLBACK_EXT = VK_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT,
        E_VIDEO_SESSION_KHR = VK_OBJECT_TYPE_VIDEO_SESSION_KHR,
        E_VIDEO_SESSION_PARAMETERS_KHR = VK_OBJECT_TYPE_VIDEO_SESSION_PARAMETERS_KHR,
        E_CU_MODULE_NVX = VK_OBJECT_TYPE_CU_MODULE_NVX,
        E_CU_FUNCTION_NVX = VK_OBJECT_TYPE_CU_FUNCTION_NVX,
        E_DEBUG_UTILS_MESSENGER_EXT = VK_OBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXT,
        E_ACCELERATION_STRUCTURE_KHR = VK_OBJECT_TYPE_ACCELERATION_STRUCTURE_KHR,
        E_VALIDATION_CACHE_EXT = VK_OBJECT_TYPE_VALIDATION_CACHE_EXT,
        E_ACCELERATION_STRUCTURE_NV = VK_OBJECT_TYPE_ACCELERATION_STRUCTURE_NV,
        E_PERFORMANCE_CONFIGURATION_INTEL = VK_OBJECT_TYPE_PERFORMANCE_CONFIGURATION_INTEL,
        E_DEFERRED_OPERATION_KHR = VK_OBJECT_TYPE_DEFERRED_OPERATION_KHR,
        E_INDIRECT_COMMANDS_LAYOUT_NV = VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NV,
        E_BUFFER_COLLECTION_FUCHSIA = VK_OBJECT_TYPE_BUFFER_COLLECTION_FUCHSIA,
        E_MICROMAP_EXT = VK_OBJECT_TYPE_MICROMAP_EXT,
        E_OPTICAL_FLOW_SESSION_NV = VK_OBJECT_TYPE_OPTICAL_FLOW_SESSION_NV,
        E_SHADER_EXT = VK_OBJECT_TYPE_SHADER_EXT,
        E_DESCRIPTOR_UPDATE_TEMPLATE_KHR = VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR,
        E_SAMPLER_YCBCR_CONVERSION_KHR = VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR,
        E_PRIVATE_DATA_SLOT_EXT = VK_OBJECT_TYPE_PRIVATE_DATA_SLOT_EXT,
    };
    
    // VkFormat
    enum class EResourceFormat : uint32 {
        E_UNDEFINED = VK_FORMAT_UNDEFINED,
        E_R4G4_UNORM_PACK8 = VK_FORMAT_R4G4_UNORM_PACK8,
        E_R4G4B4A4_UNORM_PACK16 = VK_FORMAT_R4G4B4A4_UNORM_PACK16,
        E_B4G4R4A4_UNORM_PACK16 = VK_FORMAT_B4G4R4A4_UNORM_PACK16,
        E_R5G6B5_UNORM_PACK16 = VK_FORMAT_R5G6B5_UNORM_PACK16,
        E_B5G6R5_UNORM_PACK16 = VK_FORMAT_B5G6R5_UNORM_PACK16,
        E_R5G5B5A1_UNORM_PACK16 = VK_FORMAT_R5G5B5A1_UNORM_PACK16,
        E_B5G5R5A1_UNORM_PACK16 = VK_FORMAT_B5G5R5A1_UNORM_PACK16,
        E_A1R5G5B5_UNORM_PACK16 = VK_FORMAT_A1R5G5B5_UNORM_PACK16,
        E_R8_UNORM = VK_FORMAT_R8_UNORM,
        E_R8_SNORM = VK_FORMAT_R8_SNORM,
        E_R8_USCALED = VK_FORMAT_R8_USCALED,
        E_R8_SSCALED = VK_FORMAT_R8_SSCALED,
        E_R8_UINT = VK_FORMAT_R8_UINT,
        E_R8_SINT = VK_FORMAT_R8_SINT,
        E_R8_SRGB = VK_FORMAT_R8_SRGB,
        E_R8G8_UNORM = VK_FORMAT_R8G8_UNORM,
        E_R8G8_SNORM = VK_FORMAT_R8G8_SNORM,
        E_R8G8_USCALED = VK_FORMAT_R8G8_USCALED,
        E_R8G8_SSCALED = VK_FORMAT_R8G8_SSCALED,
        E_R8G8_UINT = VK_FORMAT_R8G8_UINT,
        E_R8G8_SINT = VK_FORMAT_R8G8_SINT,
        E_R8G8_SRGB = VK_FORMAT_R8G8_SRGB,
        E_R8G8B8_UNORM = VK_FORMAT_R8G8B8_UNORM,
        E_R8G8B8_SNORM = VK_FORMAT_R8G8B8_SNORM,
        E_R8G8B8_USCALED = VK_FORMAT_R8G8B8_USCALED,
        E_R8G8B8_SSCALED = VK_FORMAT_R8G8B8_SSCALED,
        E_R8G8B8_UINT = VK_FORMAT_R8G8B8_UINT,
        E_R8G8B8_SINT = VK_FORMAT_R8G8B8_SINT,
        E_R8G8B8_SRGB = VK_FORMAT_R8G8B8_SRGB,
        E_B8G8R8_UNORM = VK_FORMAT_B8G8R8_UNORM,
        E_B8G8R8_SNORM = VK_FORMAT_B8G8R8_SNORM,
        E_B8G8R8_USCALED = VK_FORMAT_B8G8R8_USCALED,
        E_B8G8R8_SSCALED = VK_FORMAT_B8G8R8_SSCALED,
        E_B8G8R8_UINT = VK_FORMAT_B8G8R8_UINT,
        E_B8G8R8_SINT = VK_FORMAT_B8G8R8_SINT,
        E_B8G8R8_SRGB = VK_FORMAT_B8G8R8_SRGB,
        E_R8G8B8A8_UNORM = VK_FORMAT_R8G8B8A8_UNORM,
        E_R8G8B8A8_SNORM = VK_FORMAT_R8G8B8A8_SNORM,
        E_R8G8B8A8_USCALED = VK_FORMAT_R8G8B8A8_USCALED,
        E_R8G8B8A8_SSCALED = VK_FORMAT_R8G8B8A8_SSCALED,
        E_R8G8B8A8_UINT = VK_FORMAT_R8G8B8A8_UINT,
        E_R8G8B8A8_SINT = VK_FORMAT_R8G8B8A8_SINT,
        E_R8G8B8A8_SRGB = VK_FORMAT_R8G8B8A8_SRGB,
        E_B8G8R8A8_UNORM = VK_FORMAT_B8G8R8A8_UNORM,
        E_B8G8R8A8_SNORM = VK_FORMAT_B8G8R8A8_SNORM,
        E_B8G8R8A8_USCALED = VK_FORMAT_B8G8R8A8_USCALED,
        E_B8G8R8A8_SSCALED = VK_FORMAT_B8G8R8A8_SSCALED,
        E_B8G8R8A8_UINT = VK_FORMAT_B8G8R8A8_UINT,
        E_B8G8R8A8_SINT = VK_FORMAT_B8G8R8A8_SINT,
        E_B8G8R8A8_SRGB = VK_FORMAT_B8G8R8A8_SRGB,
        E_A8B8G8R8_UNORM_PACK32 = VK_FORMAT_A8B8G8R8_UNORM_PACK32,
        E_A8B8G8R8_SNORM_PACK32 = VK_FORMAT_A8B8G8R8_SNORM_PACK32,
        E_A8B8G8R8_USCALED_PACK32 = VK_FORMAT_A8B8G8R8_USCALED_PACK32,
        E_A8B8G8R8_SSCALED_PACK32 = VK_FORMAT_A8B8G8R8_SSCALED_PACK32,
        E_A8B8G8R8_UINT_PACK32 = VK_FORMAT_A8B8G8R8_UINT_PACK32,
        E_A8B8G8R8_SINT_PACK32 = VK_FORMAT_A8B8G8R8_SINT_PACK32,
        E_A8B8G8R8_SRGB_PACK32 = VK_FORMAT_A8B8G8R8_SRGB_PACK32,
        E_A2R10G10B10_UNORM_PACK32 = VK_FORMAT_A2R10G10B10_UNORM_PACK32,
        E_A2R10G10B10_SNORM_PACK32 = VK_FORMAT_A2R10G10B10_SNORM_PACK32,
        E_A2R10G10B10_USCALED_PACK32 = VK_FORMAT_A2R10G10B10_USCALED_PACK32,
        E_A2R10G10B10_SSCALED_PACK32 = VK_FORMAT_A2R10G10B10_SSCALED_PACK32,
        E_A2R10G10B10_UINT_PACK32 = VK_FORMAT_A2R10G10B10_UINT_PACK32,
        E_A2R10G10B10_SINT_PACK32 = VK_FORMAT_A2R10G10B10_SINT_PACK32,
        E_A2B10G10R10_UNORM_PACK32 = VK_FORMAT_A2B10G10R10_UNORM_PACK32,
        E_A2B10G10R10_SNORM_PACK32 = VK_FORMAT_A2B10G10R10_SNORM_PACK32,
        E_A2B10G10R10_USCALED_PACK32 = VK_FORMAT_A2B10G10R10_USCALED_PACK32,
        E_A2B10G10R10_SSCALED_PACK32 = VK_FORMAT_A2B10G10R10_SSCALED_PACK32,
        E_A2B10G10R10_UINT_PACK32 = VK_FORMAT_A2B10G10R10_UINT_PACK32,
        E_A2B10G10R10_SINT_PACK32 = VK_FORMAT_A2B10G10R10_SINT_PACK32,
        E_R16_UNORM = VK_FORMAT_R16_UNORM,
        E_R16_SNORM = VK_FORMAT_R16_SNORM,
        E_R16_USCALED = VK_FORMAT_R16_USCALED,
        E_R16_SSCALED = VK_FORMAT_R16_SSCALED,
        E_R16_UINT = VK_FORMAT_R16_UINT,
        E_R16_SINT = VK_FORMAT_R16_SINT,
        E_R16_SFLOAT = VK_FORMAT_R16_SFLOAT,
        E_R16G16_UNORM = VK_FORMAT_R16G16_UNORM,
        E_R16G16_SNORM = VK_FORMAT_R16G16_SNORM,
        E_R16G16_USCALED = VK_FORMAT_R16G16_USCALED,
        E_R16G16_SSCALED = VK_FORMAT_R16G16_SSCALED,
        E_R16G16_UINT = VK_FORMAT_R16G16_UINT,
        E_R16G16_SINT = VK_FORMAT_R16G16_SINT,
        E_R16G16_SFLOAT = VK_FORMAT_R16G16_SFLOAT,
        E_R16G16B16_UNORM = VK_FORMAT_R16G16B16_UNORM,
        E_R16G16B16_SNORM = VK_FORMAT_R16G16B16_SNORM,
        E_R16G16B16_USCALED = VK_FORMAT_R16G16B16_USCALED,
        E_R16G16B16_SSCALED = VK_FORMAT_R16G16B16_SSCALED,
        E_R16G16B16_UINT = VK_FORMAT_R16G16B16_UINT,
        E_R16G16B16_SINT = VK_FORMAT_R16G16B16_SINT,
        E_R16G16B16_SFLOAT = VK_FORMAT_R16G16B16_SFLOAT,
        E_R16G16B16A16_UNORM = VK_FORMAT_R16G16B16A16_UNORM,
        E_R16G16B16A16_SNORM = VK_FORMAT_R16G16B16A16_SNORM,
        E_R16G16B16A16_USCALED = VK_FORMAT_R16G16B16A16_USCALED,
        E_R16G16B16A16_SSCALED = VK_FORMAT_R16G16B16A16_SSCALED,
        E_R16G16B16A16_UINT = VK_FORMAT_R16G16B16A16_UINT,
        E_R16G16B16A16_SINT = VK_FORMAT_R16G16B16A16_SINT,
        E_R16G16B16A16_SFLOAT = VK_FORMAT_R16G16B16A16_SFLOAT,
        E_R32_UINT = VK_FORMAT_R32_UINT,
        E_R32_SINT = VK_FORMAT_R32_SINT,
        E_R32_SFLOAT = VK_FORMAT_R32_SFLOAT,
        E_R32G32_UINT = VK_FORMAT_R32G32_UINT,
        E_R32G32_SINT = VK_FORMAT_R32G32_SINT,
        E_R32G32_SFLOAT = VK_FORMAT_R32G32_SFLOAT,
        E_R32G32B32_UINT = VK_FORMAT_R32G32B32_UINT,
        E_R32G32B32_SINT = VK_FORMAT_R32G32B32_SINT,
        E_R32G32B32_SFLOAT = VK_FORMAT_R32G32B32_SFLOAT,
        E_R32G32B32A32_UINT = VK_FORMAT_R32G32B32A32_UINT,
        E_R32G32B32A32_SINT = VK_FORMAT_R32G32B32A32_SINT,
        E_R32G32B32A32_SFLOAT = VK_FORMAT_R32G32B32A32_SFLOAT,
        E_R64_UINT = VK_FORMAT_R64_UINT,
        E_R64_SINT = VK_FORMAT_R64_SINT,
        E_R64_SFLOAT = VK_FORMAT_R64_SFLOAT,
        E_R64G64_UINT = VK_FORMAT_R64G64_UINT,
        E_R64G64_SINT = VK_FORMAT_R64G64_SINT,
        E_R64G64_SFLOAT = VK_FORMAT_R64G64_SFLOAT,
        E_R64G64B64_UINT = VK_FORMAT_R64G64B64_UINT,
        E_R64G64B64_SINT = VK_FORMAT_R64G64B64_SINT,
        E_R64G64B64_SFLOAT = VK_FORMAT_R64G64B64_SFLOAT,
        E_R64G64B64A64_UINT = VK_FORMAT_R64G64B64A64_UINT,
        E_R64G64B64A64_SINT = VK_FORMAT_R64G64B64A64_SINT,
        E_R64G64B64A64_SFLOAT = VK_FORMAT_R64G64B64A64_SFLOAT,
        E_B10G11R11_UFLOAT_PACK32 = VK_FORMAT_B10G11R11_UFLOAT_PACK32,
        E_E5B9G9R9_UFLOAT_PACK32 = VK_FORMAT_E5B9G9R9_UFLOAT_PACK32,
        E_D16_UNORM = VK_FORMAT_D16_UNORM,
        E_X8_D24_UNORM_PACK32 = VK_FORMAT_X8_D24_UNORM_PACK32,
        E_D32_SFLOAT = VK_FORMAT_D32_SFLOAT,
        E_S8_UINT = VK_FORMAT_S8_UINT,
        E_D16_UNORM_S8_UINT = VK_FORMAT_D16_UNORM_S8_UINT,
        E_D24_UNORM_S8_UINT = VK_FORMAT_D24_UNORM_S8_UINT,
        E_D32_SFLOAT_S8_UINT = VK_FORMAT_D32_SFLOAT_S8_UINT,
        E_BC1_RGB_UNORM_BLOCK = VK_FORMAT_BC1_RGB_UNORM_BLOCK,
        E_BC1_RGB_SRGB_BLOCK = VK_FORMAT_BC1_RGB_SRGB_BLOCK,
        E_BC1_RGBA_UNORM_BLOCK = VK_FORMAT_BC1_RGBA_UNORM_BLOCK,
        E_BC1_RGBA_SRGB_BLOCK = VK_FORMAT_BC1_RGBA_SRGB_BLOCK,
        E_BC2_UNORM_BLOCK = VK_FORMAT_BC2_UNORM_BLOCK,
        E_BC2_SRGB_BLOCK = VK_FORMAT_BC2_SRGB_BLOCK,
        E_BC3_UNORM_BLOCK = VK_FORMAT_BC3_UNORM_BLOCK,
        E_BC3_SRGB_BLOCK = VK_FORMAT_BC3_SRGB_BLOCK,
        E_BC4_UNORM_BLOCK = VK_FORMAT_BC4_UNORM_BLOCK,
        E_BC4_SNORM_BLOCK = VK_FORMAT_BC4_SNORM_BLOCK,
        E_BC5_UNORM_BLOCK = VK_FORMAT_BC5_UNORM_BLOCK,
        E_BC5_SNORM_BLOCK = VK_FORMAT_BC5_SNORM_BLOCK,
        E_BC6H_UFLOAT_BLOCK = VK_FORMAT_BC6H_UFLOAT_BLOCK,
        E_BC6H_SFLOAT_BLOCK = VK_FORMAT_BC6H_SFLOAT_BLOCK,
        E_BC7_UNORM_BLOCK = VK_FORMAT_BC7_UNORM_BLOCK,
        E_BC7_SRGB_BLOCK = VK_FORMAT_BC7_SRGB_BLOCK,
        E_ETC2_R8G8B8_UNORM_BLOCK = VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK,
        E_ETC2_R8G8B8_SRGB_BLOCK = VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK,
        E_ETC2_R8G8B8A1_UNORM_BLOCK = VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK,
        E_ETC2_R8G8B8A1_SRGB_BLOCK = VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK,
        E_ETC2_R8G8B8A8_UNORM_BLOCK = VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK,
        E_ETC2_R8G8B8A8_SRGB_BLOCK = VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK,
        E_EAC_R11_UNORM_BLOCK = VK_FORMAT_EAC_R11_UNORM_BLOCK,
        E_EAC_R11_SNORM_BLOCK = VK_FORMAT_EAC_R11_SNORM_BLOCK,
        E_EAC_R11G11_UNORM_BLOCK = VK_FORMAT_EAC_R11G11_UNORM_BLOCK,
        E_EAC_R11G11_SNORM_BLOCK = VK_FORMAT_EAC_R11G11_SNORM_BLOCK,
        E_ASTC_4x4_UNORM_BLOCK = VK_FORMAT_ASTC_4x4_UNORM_BLOCK,
        E_ASTC_4x4_SRGB_BLOCK = VK_FORMAT_ASTC_4x4_SRGB_BLOCK,
        E_ASTC_5x4_UNORM_BLOCK = VK_FORMAT_ASTC_5x4_UNORM_BLOCK,
        E_ASTC_5x4_SRGB_BLOCK = VK_FORMAT_ASTC_5x4_SRGB_BLOCK,
        E_ASTC_5x5_UNORM_BLOCK = VK_FORMAT_ASTC_5x5_UNORM_BLOCK,
        E_ASTC_5x5_SRGB_BLOCK = VK_FORMAT_ASTC_5x5_SRGB_BLOCK,
        E_ASTC_6x5_UNORM_BLOCK = VK_FORMAT_ASTC_6x5_UNORM_BLOCK,
        E_ASTC_6x5_SRGB_BLOCK = VK_FORMAT_ASTC_6x5_SRGB_BLOCK,
        E_ASTC_6x6_UNORM_BLOCK = VK_FORMAT_ASTC_6x6_UNORM_BLOCK,
        E_ASTC_6x6_SRGB_BLOCK = VK_FORMAT_ASTC_6x6_SRGB_BLOCK,
        E_ASTC_8x5_UNORM_BLOCK = VK_FORMAT_ASTC_8x5_UNORM_BLOCK,
        E_ASTC_8x5_SRGB_BLOCK = VK_FORMAT_ASTC_8x5_SRGB_BLOCK,
        E_ASTC_8x6_UNORM_BLOCK = VK_FORMAT_ASTC_8x6_UNORM_BLOCK,
        E_ASTC_8x6_SRGB_BLOCK = VK_FORMAT_ASTC_8x6_SRGB_BLOCK,
        E_ASTC_8x8_UNORM_BLOCK = VK_FORMAT_ASTC_8x8_UNORM_BLOCK,
        E_ASTC_8x8_SRGB_BLOCK = VK_FORMAT_ASTC_8x8_SRGB_BLOCK,
        E_ASTC_10x5_UNORM_BLOCK = VK_FORMAT_ASTC_10x5_UNORM_BLOCK,
        E_ASTC_10x5_SRGB_BLOCK = VK_FORMAT_ASTC_10x5_SRGB_BLOCK,
        E_ASTC_10x6_UNORM_BLOCK = VK_FORMAT_ASTC_10x6_UNORM_BLOCK,
        E_ASTC_10x6_SRGB_BLOCK = VK_FORMAT_ASTC_10x6_SRGB_BLOCK,
        E_ASTC_10x8_UNORM_BLOCK = VK_FORMAT_ASTC_10x8_UNORM_BLOCK,
        E_ASTC_10x8_SRGB_BLOCK = VK_FORMAT_ASTC_10x8_SRGB_BLOCK,
        E_ASTC_10x10_UNORM_BLOCK = VK_FORMAT_ASTC_10x10_UNORM_BLOCK,
        E_ASTC_10x10_SRGB_BLOCK = VK_FORMAT_ASTC_10x10_SRGB_BLOCK,
        E_ASTC_12x10_UNORM_BLOCK = VK_FORMAT_ASTC_12x10_UNORM_BLOCK,
        E_ASTC_12x10_SRGB_BLOCK = VK_FORMAT_ASTC_12x10_SRGB_BLOCK,
        E_ASTC_12x12_UNORM_BLOCK = VK_FORMAT_ASTC_12x12_UNORM_BLOCK,
        E_ASTC_12x12_SRGB_BLOCK = VK_FORMAT_ASTC_12x12_SRGB_BLOCK,
        E_G8B8G8R8_422_UNORM = VK_FORMAT_G8B8G8R8_422_UNORM,
        E_B8G8R8G8_422_UNORM = VK_FORMAT_B8G8R8G8_422_UNORM,
        E_G8_B8_R8_3PLANE_420_UNORM = VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM,
        E_G8_B8R8_2PLANE_420_UNORM = VK_FORMAT_G8_B8R8_2PLANE_420_UNORM,
        E_G8_B8_R8_3PLANE_422_UNORM = VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM,
        E_G8_B8R8_2PLANE_422_UNORM = VK_FORMAT_G8_B8R8_2PLANE_422_UNORM,
        E_G8_B8_R8_3PLANE_444_UNORM = VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM,
        E_R10X6_UNORM_PACK16 = VK_FORMAT_R10X6_UNORM_PACK16,
        E_R10X6G10X6_UNORM_2PACK16 = VK_FORMAT_R10X6G10X6_UNORM_2PACK16,
        E_R10X6G10X6B10X6A10X6_UNORM_4PACK16 = VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16,
        E_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16 = VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16,
        E_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16 = VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16,
        E_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16 = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16,
        E_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16 = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16,
        E_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16 = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16,
        E_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16 = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16,
        E_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16 = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16,
        E_R12X4_UNORM_PACK16 = VK_FORMAT_R12X4_UNORM_PACK16,
        E_R12X4G12X4_UNORM_2PACK16 = VK_FORMAT_R12X4G12X4_UNORM_2PACK16,
        E_R12X4G12X4B12X4A12X4_UNORM_4PACK16 = VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16,
        E_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16 = VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16,
        E_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16 = VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16,
        E_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16 = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16,
        E_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16 = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16,
        E_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16 = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16,
        E_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16 = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16,
        E_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16 = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16,
        E_G16B16G16R16_422_UNORM = VK_FORMAT_G16B16G16R16_422_UNORM,
        E_B16G16R16G16_422_UNORM = VK_FORMAT_B16G16R16G16_422_UNORM,
        E_G16_B16_R16_3PLANE_420_UNORM = VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM,
        E_G16_B16R16_2PLANE_420_UNORM = VK_FORMAT_G16_B16R16_2PLANE_420_UNORM,
        E_G16_B16_R16_3PLANE_422_UNORM = VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM,
        E_G16_B16R16_2PLANE_422_UNORM = VK_FORMAT_G16_B16R16_2PLANE_422_UNORM,
        E_G16_B16_R16_3PLANE_444_UNORM = VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM,
        E_G8_B8R8_2PLANE_444_UNORM = VK_FORMAT_G8_B8R8_2PLANE_444_UNORM,
        E_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16 = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16,
        E_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16 = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16,
        E_G16_B16R16_2PLANE_444_UNORM = VK_FORMAT_G16_B16R16_2PLANE_444_UNORM,
        E_A4R4G4B4_UNORM_PACK16 = VK_FORMAT_A4R4G4B4_UNORM_PACK16,
        E_A4B4G4R4_UNORM_PACK16 = VK_FORMAT_A4B4G4R4_UNORM_PACK16,
        E_ASTC_4x4_SFLOAT_BLOCK = VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK,
        E_ASTC_5x4_SFLOAT_BLOCK = VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK,
        E_ASTC_5x5_SFLOAT_BLOCK = VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK,
        E_ASTC_6x5_SFLOAT_BLOCK = VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK,
        E_ASTC_6x6_SFLOAT_BLOCK = VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK,
        E_ASTC_8x5_SFLOAT_BLOCK = VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK,
        E_ASTC_8x6_SFLOAT_BLOCK = VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK,
        E_ASTC_8x8_SFLOAT_BLOCK = VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK,
        E_ASTC_10x5_SFLOAT_BLOCK = VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK,
        E_ASTC_10x6_SFLOAT_BLOCK = VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK,
        E_ASTC_10x8_SFLOAT_BLOCK = VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK,
        E_ASTC_10x10_SFLOAT_BLOCK = VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK,
        E_ASTC_12x10_SFLOAT_BLOCK = VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK,
        E_ASTC_12x12_SFLOAT_BLOCK = VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK,
        E_PVRTC1_2BPP_UNORM_BLOCK_IMG = VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG,
        E_PVRTC1_4BPP_UNORM_BLOCK_IMG = VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG,
        E_PVRTC2_2BPP_UNORM_BLOCK_IMG = VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG,
        E_PVRTC2_4BPP_UNORM_BLOCK_IMG = VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG,
        E_PVRTC1_2BPP_SRGB_BLOCK_IMG = VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG,
        E_PVRTC1_4BPP_SRGB_BLOCK_IMG = VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG,
        E_PVRTC2_2BPP_SRGB_BLOCK_IMG = VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG,
        E_PVRTC2_4BPP_SRGB_BLOCK_IMG = VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG,
        E_R16G16_S10_5_NV = VK_FORMAT_R16G16_S10_5_NV,
        E_ASTC_4x4_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_4x4_SFLOAT_BLOCK_EXT,
        E_ASTC_5x4_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_5x4_SFLOAT_BLOCK_EXT,
        E_ASTC_5x5_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_5x5_SFLOAT_BLOCK_EXT,
        E_ASTC_6x5_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_6x5_SFLOAT_BLOCK_EXT,
        E_ASTC_6x6_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_6x6_SFLOAT_BLOCK_EXT,
        E_ASTC_8x5_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_8x5_SFLOAT_BLOCK_EXT,
        E_ASTC_8x6_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_8x6_SFLOAT_BLOCK_EXT,
        E_ASTC_8x8_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_8x8_SFLOAT_BLOCK_EXT,
        E_ASTC_10x5_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_10x5_SFLOAT_BLOCK_EXT,
        E_ASTC_10x6_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_10x6_SFLOAT_BLOCK_EXT,
        E_ASTC_10x8_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_10x8_SFLOAT_BLOCK_EXT,
        E_ASTC_10x10_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_10x10_SFLOAT_BLOCK_EXT,
        E_ASTC_12x10_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_12x10_SFLOAT_BLOCK_EXT,
        E_ASTC_12x12_SFLOAT_BLOCK_EXT = VK_FORMAT_ASTC_12x12_SFLOAT_BLOCK_EXT,
        E_G8B8G8R8_422_UNORM_KHR = VK_FORMAT_G8B8G8R8_422_UNORM_KHR,
        E_B8G8R8G8_422_UNORM_KHR = VK_FORMAT_B8G8R8G8_422_UNORM_KHR,
        E_G8_B8_R8_3PLANE_420_UNORM_KHR = VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR,
        E_G8_B8R8_2PLANE_420_UNORM_KHR = VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR,
        E_G8_B8_R8_3PLANE_422_UNORM_KHR = VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR,
        E_G8_B8R8_2PLANE_422_UNORM_KHR = VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR,
        E_G8_B8_R8_3PLANE_444_UNORM_KHR = VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR,
        E_R10X6_UNORM_PACK16_KHR = VK_FORMAT_R10X6_UNORM_PACK16_KHR,
        E_R10X6G10X6_UNORM_2PACK16_KHR = VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR,
        E_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR = VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR,
        E_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR = VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR,
        E_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR = VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR,
        E_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR,
        E_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR,
        E_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR,
        E_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR,
        E_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR,
        E_R12X4_UNORM_PACK16_KHR = VK_FORMAT_R12X4_UNORM_PACK16_KHR,
        E_R12X4G12X4_UNORM_2PACK16_KHR = VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR,
        E_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR = VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR,
        E_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR = VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR,
        E_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR = VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR,
        E_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR,
        E_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR,
        E_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR,
        E_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR,
        E_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR,
        E_G16B16G16R16_422_UNORM_KHR = VK_FORMAT_G16B16G16R16_422_UNORM_KHR,
        E_B16G16R16G16_422_UNORM_KHR = VK_FORMAT_B16G16R16G16_422_UNORM_KHR,
        E_G16_B16_R16_3PLANE_420_UNORM_KHR = VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR,
        E_G16_B16R16_2PLANE_420_UNORM_KHR = VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR,
        E_G16_B16_R16_3PLANE_422_UNORM_KHR = VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR,
        E_G16_B16R16_2PLANE_422_UNORM_KHR = VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR,
        E_G16_B16_R16_3PLANE_444_UNORM_KHR = VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR,
        E_G8_B8R8_2PLANE_444_UNORM_EXT = VK_FORMAT_G8_B8R8_2PLANE_444_UNORM_EXT,
        E_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16_EXT,
        E_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16_EXT,
        E_G16_B16R16_2PLANE_444_UNORM_EXT = VK_FORMAT_G16_B16R16_2PLANE_444_UNORM_EXT,
        E_A4R4G4B4_UNORM_PACK16_EXT = VK_FORMAT_A4R4G4B4_UNORM_PACK16_EXT,
        E_A4B4G4R4_UNORM_PACK16_EXT = VK_FORMAT_A4B4G4R4_UNORM_PACK16_EXT,
    };

    // VkQueryType
    enum class EQueryType : uint32 {
        E_OCCLUSION = VK_QUERY_TYPE_OCCLUSION,
        E_PIPELINE_STATISTICS = VK_QUERY_TYPE_PIPELINE_STATISTICS,
        E_TIMESTAMP = VK_QUERY_TYPE_TIMESTAMP,
        E_RESULT_STATUS_ONLY_KHR = VK_QUERY_TYPE_RESULT_STATUS_ONLY_KHR,
        E_TRANSFORM_FEEDBACK_STREAM_EXT = VK_QUERY_TYPE_TRANSFORM_FEEDBACK_STREAM_EXT,
        E_PERFORMANCE_QUERY_KHR = VK_QUERY_TYPE_PERFORMANCE_QUERY_KHR,
        E_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR = VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_KHR,
        E_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR = VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_SIZE_KHR,
        E_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV = VK_QUERY_TYPE_ACCELERATION_STRUCTURE_COMPACTED_SIZE_NV,
        E_PERFORMANCE_QUERY_INTEL = VK_QUERY_TYPE_PERFORMANCE_QUERY_INTEL,
        E_MESH_PRIMITIVES_GENERATED_EXT = VK_QUERY_TYPE_MESH_PRIMITIVES_GENERATED_EXT,
        E_PRIMITIVES_GENERATED_EXT = VK_QUERY_TYPE_PRIMITIVES_GENERATED_EXT,
        E_ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS_KHR = VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SERIALIZATION_BOTTOM_LEVEL_POINTERS_KHR,
        E_ACCELERATION_STRUCTURE_SIZE_KHR = VK_QUERY_TYPE_ACCELERATION_STRUCTURE_SIZE_KHR,
        E_MICROMAP_SERIALIZATION_SIZE_EXT = VK_QUERY_TYPE_MICROMAP_SERIALIZATION_SIZE_EXT,
        E_MICROMAP_COMPACTED_SIZE_EXT = VK_QUERY_TYPE_MICROMAP_COMPACTED_SIZE_EXT,
    };

    // VkComponentSwizzle
    enum class EComponentSwizzle : uint32 {
        E_IDENTITY = VK_COMPONENT_SWIZZLE_IDENTITY,
        E_ZERO = VK_COMPONENT_SWIZZLE_ZERO,
        E_ONE = VK_COMPONENT_SWIZZLE_ONE,
        E_R = VK_COMPONENT_SWIZZLE_R,
        E_G = VK_COMPONENT_SWIZZLE_G,
        E_B = VK_COMPONENT_SWIZZLE_B,
        E_A = VK_COMPONENT_SWIZZLE_A,
    };

    // VkBlendFactor
    enum class EBlendFactor : uint32 {
        E_ZERO = VK_BLEND_FACTOR_ZERO,
        E_ONE = VK_BLEND_FACTOR_ONE,
        E_SRC_COLOR = VK_BLEND_FACTOR_SRC_COLOR,
        E_ONE_MINUS_SRC_COLOR = VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR,
        E_DST_COLOR = VK_BLEND_FACTOR_DST_COLOR,
        E_ONE_MINUS_DST_COLOR = VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR,
        E_SRC_ALPHA = VK_BLEND_FACTOR_SRC_ALPHA,
        E_ONE_MINUS_SRC_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA,
        E_DST_ALPHA = VK_BLEND_FACTOR_DST_ALPHA,
        E_ONE_MINUS_DST_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA,
        E_CONSTANT_COLOR = VK_BLEND_FACTOR_CONSTANT_COLOR,
        E_ONE_MINUS_CONSTANT_COLOR = VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR,
        E_CONSTANT_ALPHA = VK_BLEND_FACTOR_CONSTANT_ALPHA,
        E_ONE_MINUS_CONSTANT_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA,
        E_SRC_ALPHA_SATURATE = VK_BLEND_FACTOR_SRC_ALPHA_SATURATE,
        E_SRC1_COLOR = VK_BLEND_FACTOR_SRC1_COLOR,
        E_ONE_MINUS_SRC1_COLOR = VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR,
        E_SRC1_ALPHA = VK_BLEND_FACTOR_SRC1_ALPHA,
        E_ONE_MINUS_SRC1_ALPHA = VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA,
    };

    // VkBlendOp
    enum class EBlendOperator : uint32 {
        E_ADD = VK_BLEND_OP_ADD,
        E_SUBTRACT = VK_BLEND_OP_SUBTRACT,
        E_REVERSE_SUBTRACT = VK_BLEND_OP_REVERSE_SUBTRACT,
        E_MIN = VK_BLEND_OP_MIN,
        E_MAX = VK_BLEND_OP_MAX,
        E_ZERO_EXT = VK_BLEND_OP_ZERO_EXT,
        E_SRC_EXT = VK_BLEND_OP_SRC_EXT,
        E_DST_EXT = VK_BLEND_OP_DST_EXT,
        E_SRC_OVER_EXT = VK_BLEND_OP_SRC_OVER_EXT,
        E_DST_OVER_EXT = VK_BLEND_OP_DST_OVER_EXT,
        E_SRC_IN_EXT = VK_BLEND_OP_SRC_IN_EXT,
        E_DST_IN_EXT = VK_BLEND_OP_DST_IN_EXT,
        E_SRC_OUT_EXT = VK_BLEND_OP_SRC_OUT_EXT,
        E_DST_OUT_EXT = VK_BLEND_OP_DST_OUT_EXT,
        E_SRC_ATOP_EXT = VK_BLEND_OP_SRC_ATOP_EXT,
        E_DST_ATOP_EXT = VK_BLEND_OP_DST_ATOP_EXT,
        E_XOR_EXT = VK_BLEND_OP_XOR_EXT,
        E_MULTIPLY_EXT = VK_BLEND_OP_MULTIPLY_EXT,
        E_SCREEN_EXT = VK_BLEND_OP_SCREEN_EXT,
        E_OVERLAY_EXT = VK_BLEND_OP_OVERLAY_EXT,
        E_DARKEN_EXT = VK_BLEND_OP_DARKEN_EXT,
        E_LIGHTEN_EXT = VK_BLEND_OP_LIGHTEN_EXT,
        E_COLORDODGE_EXT = VK_BLEND_OP_COLORDODGE_EXT,
        E_COLORBURN_EXT = VK_BLEND_OP_COLORBURN_EXT,
        E_HARDLIGHT_EXT = VK_BLEND_OP_HARDLIGHT_EXT,
        E_SOFTLIGHT_EXT = VK_BLEND_OP_SOFTLIGHT_EXT,
        E_DIFFERENCE_EXT = VK_BLEND_OP_DIFFERENCE_EXT,
        E_EXCLUSION_EXT = VK_BLEND_OP_EXCLUSION_EXT,
        E_INVERT_EXT = VK_BLEND_OP_INVERT_EXT,
        E_INVERT_RGB_EXT = VK_BLEND_OP_INVERT_RGB_EXT,
        E_LINEARDODGE_EXT = VK_BLEND_OP_LINEARDODGE_EXT,
        E_LINEARBURN_EXT = VK_BLEND_OP_LINEARBURN_EXT,
        E_VIVIDLIGHT_EXT = VK_BLEND_OP_VIVIDLIGHT_EXT,
        E_LINEARLIGHT_EXT = VK_BLEND_OP_LINEARLIGHT_EXT,
        E_PINLIGHT_EXT = VK_BLEND_OP_PINLIGHT_EXT,
        E_HARDMIX_EXT = VK_BLEND_OP_HARDMIX_EXT,
        E_HSL_HUE_EXT = VK_BLEND_OP_HSL_HUE_EXT,
        E_HSL_SATURATION_EXT = VK_BLEND_OP_HSL_SATURATION_EXT,
        E_HSL_COLOR_EXT = VK_BLEND_OP_HSL_COLOR_EXT,
        E_HSL_LUMINOSITY_EXT = VK_BLEND_OP_HSL_LUMINOSITY_EXT,
        E_PLUS_EXT = VK_BLEND_OP_PLUS_EXT,
        E_PLUS_CLAMPED_EXT = VK_BLEND_OP_PLUS_CLAMPED_EXT,
        E_PLUS_CLAMPED_ALPHA_EXT = VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT,
        E_PLUS_DARKER_EXT = VK_BLEND_OP_PLUS_DARKER_EXT,
        E_MINUS_EXT = VK_BLEND_OP_MINUS_EXT,
        E_MINUS_CLAMPED_EXT = VK_BLEND_OP_MINUS_CLAMPED_EXT,
        E_CONTRAST_EXT = VK_BLEND_OP_CONTRAST_EXT,
        E_INVERT_OVG_EXT = VK_BLEND_OP_INVERT_OVG_EXT,
        E_RED_EXT = VK_BLEND_OP_RED_EXT,
        E_GREEN_EXT = VK_BLEND_OP_GREEN_EXT,
        E_BLUE_EXT = VK_BLEND_OP_BLUE_EXT,
    };

    // VkCompareOp
    enum class ECompareOperator : uint32 {
        E_NEVER = VK_COMPARE_OP_NEVER,
        E_LESS = VK_COMPARE_OP_LESS,
        E_EQUAL = VK_COMPARE_OP_EQUAL,
        E_LESS_OR_EQUAL = VK_COMPARE_OP_LESS_OR_EQUAL,
        E_GREATER = VK_COMPARE_OP_GREATER,
        E_NOT_EQUAL = VK_COMPARE_OP_NOT_EQUAL,
        E_GREATER_OR_EQUAL = VK_COMPARE_OP_GREATER_OR_EQUAL,
        E_ALWAYS = VK_COMPARE_OP_ALWAYS,
    };

    // VkDynamicState
    enum class EDynamicState : uint32 {
        E_VIEWPORT = VK_DYNAMIC_STATE_VIEWPORT,
        E_SCISSOR = VK_DYNAMIC_STATE_SCISSOR,
        E_LINE_WIDTH = VK_DYNAMIC_STATE_LINE_WIDTH,
        E_DEPTH_BIAS = VK_DYNAMIC_STATE_DEPTH_BIAS,
        E_BLEND_CONSTANTS = VK_DYNAMIC_STATE_BLEND_CONSTANTS,
        E_DEPTH_BOUNDS = VK_DYNAMIC_STATE_DEPTH_BOUNDS,
        E_STENCIL_COMPARE_MASK = VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK,
        E_STENCIL_WRITE_MASK = VK_DYNAMIC_STATE_STENCIL_WRITE_MASK,
        E_STENCIL_REFERENCE = VK_DYNAMIC_STATE_STENCIL_REFERENCE,
        E_CULL_MODE = VK_DYNAMIC_STATE_CULL_MODE,
        E_FRONT_FACE = VK_DYNAMIC_STATE_FRONT_FACE,
        E_PRIMITIVE_TOPOLOGY = VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY,
        E_VIEWPORT_WITH_COUNT = VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT,
        E_SCISSOR_WITH_COUNT = VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT,
        E_VERTEX_INPUT_BINDING_STRIDE = VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE,
        E_DEPTH_TEST_ENABLE = VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE,
        E_DEPTH_WRITE_ENABLE = VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE,
        E_DEPTH_COMPARE_OP = VK_DYNAMIC_STATE_DEPTH_COMPARE_OP,
        E_DEPTH_BOUNDS_TEST_ENABLE = VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE,
        E_STENCIL_TEST_ENABLE = VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE,
        E_STENCIL_OP = VK_DYNAMIC_STATE_STENCIL_OP,
        E_RASTERIZER_DISCARD_ENABLE = VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE,
        E_DEPTH_BIAS_ENABLE = VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE,
        E_PRIMITIVE_RESTART_ENABLE = VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE,
        E_VIEWPORT_W_SCALING_NV = VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV,
        E_DISCARD_RECTANGLE_EXT = VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT,
        E_DISCARD_RECTANGLE_ENABLE_EXT = VK_DYNAMIC_STATE_DISCARD_RECTANGLE_ENABLE_EXT,
        E_DISCARD_RECTANGLE_MODE_EXT = VK_DYNAMIC_STATE_DISCARD_RECTANGLE_MODE_EXT,
        E_SAMPLE_LOCATIONS_EXT = VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT,
        E_RAY_TRACING_PIPELINE_STACK_SIZE_KHR = VK_DYNAMIC_STATE_RAY_TRACING_PIPELINE_STACK_SIZE_KHR,
        E_VIEWPORT_SHADING_RATE_PALETTE_NV = VK_DYNAMIC_STATE_VIEWPORT_SHADING_RATE_PALETTE_NV,
        E_VIEWPORT_COARSE_SAMPLE_ORDER_NV = VK_DYNAMIC_STATE_VIEWPORT_COARSE_SAMPLE_ORDER_NV,
        E_EXCLUSIVE_SCISSOR_ENABLE_NV = VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV,
        E_EXCLUSIVE_SCISSOR_NV = VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_NV,
        E_FRAGMENT_SHADING_RATE_KHR = VK_DYNAMIC_STATE_FRAGMENT_SHADING_RATE_KHR,
        E_LINE_STIPPLE_EXT = VK_DYNAMIC_STATE_LINE_STIPPLE_EXT,
        E_VERTEX_INPUT_EXT = VK_DYNAMIC_STATE_VERTEX_INPUT_EXT,
        E_PATCH_CONTROL_POINTS_EXT = VK_DYNAMIC_STATE_PATCH_CONTROL_POINTS_EXT,
        E_LOGIC_OP_EXT = VK_DYNAMIC_STATE_LOGIC_OP_EXT,
        E_COLOR_WRITE_ENABLE_EXT = VK_DYNAMIC_STATE_COLOR_WRITE_ENABLE_EXT,
        E_TESSELLATION_DOMAIN_ORIGIN_EXT = VK_DYNAMIC_STATE_TESSELLATION_DOMAIN_ORIGIN_EXT,
        E_DEPTH_CLAMP_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_CLAMP_ENABLE_EXT,
        E_POLYGON_MODE_EXT = VK_DYNAMIC_STATE_POLYGON_MODE_EXT,
        E_RASTERIZATION_SAMPLES_EXT = VK_DYNAMIC_STATE_RASTERIZATION_SAMPLES_EXT,
        E_SAMPLE_MASK_EXT = VK_DYNAMIC_STATE_SAMPLE_MASK_EXT,
        E_ALPHA_TO_COVERAGE_ENABLE_EXT = VK_DYNAMIC_STATE_ALPHA_TO_COVERAGE_ENABLE_EXT,
        E_ALPHA_TO_ONE_ENABLE_EXT = VK_DYNAMIC_STATE_ALPHA_TO_ONE_ENABLE_EXT,
        E_LOGIC_OP_ENABLE_EXT = VK_DYNAMIC_STATE_LOGIC_OP_ENABLE_EXT,
        E_COLOR_BLEND_ENABLE_EXT = VK_DYNAMIC_STATE_COLOR_BLEND_ENABLE_EXT,
        E_COLOR_BLEND_EQUATION_EXT = VK_DYNAMIC_STATE_COLOR_BLEND_EQUATION_EXT,
        E_COLOR_WRITE_MASK_EXT = VK_DYNAMIC_STATE_COLOR_WRITE_MASK_EXT,
        E_RASTERIZATION_STREAM_EXT = VK_DYNAMIC_STATE_RASTERIZATION_STREAM_EXT,
        E_CONSERVATIVE_RASTERIZATION_MODE_EXT = VK_DYNAMIC_STATE_CONSERVATIVE_RASTERIZATION_MODE_EXT,
        E_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT = VK_DYNAMIC_STATE_EXTRA_PRIMITIVE_OVERESTIMATION_SIZE_EXT,
        E_DEPTH_CLIP_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT,
        E_SAMPLE_LOCATIONS_ENABLE_EXT = VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_ENABLE_EXT,
        E_COLOR_BLEND_ADVANCED_EXT = VK_DYNAMIC_STATE_COLOR_BLEND_ADVANCED_EXT,
        E_PROVOKING_VERTEX_MODE_EXT = VK_DYNAMIC_STATE_PROVOKING_VERTEX_MODE_EXT,
        E_LINE_RASTERIZATION_MODE_EXT = VK_DYNAMIC_STATE_LINE_RASTERIZATION_MODE_EXT,
        E_LINE_STIPPLE_ENABLE_EXT = VK_DYNAMIC_STATE_LINE_STIPPLE_ENABLE_EXT,
        E_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT = VK_DYNAMIC_STATE_DEPTH_CLIP_NEGATIVE_ONE_TO_ONE_EXT,
        E_VIEWPORT_W_SCALING_ENABLE_NV = VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_ENABLE_NV,
        E_VIEWPORT_SWIZZLE_NV = VK_DYNAMIC_STATE_VIEWPORT_SWIZZLE_NV,
        E_COVERAGE_TO_COLOR_ENABLE_NV = VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_ENABLE_NV,
        E_COVERAGE_TO_COLOR_LOCATION_NV = VK_DYNAMIC_STATE_COVERAGE_TO_COLOR_LOCATION_NV,
        E_COVERAGE_MODULATION_MODE_NV = VK_DYNAMIC_STATE_COVERAGE_MODULATION_MODE_NV,
        E_COVERAGE_MODULATION_TABLE_ENABLE_NV = VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_ENABLE_NV,
        E_COVERAGE_MODULATION_TABLE_NV = VK_DYNAMIC_STATE_COVERAGE_MODULATION_TABLE_NV,
        E_SHADING_RATE_IMAGE_ENABLE_NV = VK_DYNAMIC_STATE_SHADING_RATE_IMAGE_ENABLE_NV,
        E_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV = VK_DYNAMIC_STATE_REPRESENTATIVE_FRAGMENT_TEST_ENABLE_NV,
        E_COVERAGE_REDUCTION_MODE_NV = VK_DYNAMIC_STATE_COVERAGE_REDUCTION_MODE_NV,
        E_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT = VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT,
        E_CULL_MODE_EXT = VK_DYNAMIC_STATE_CULL_MODE_EXT,
        E_FRONT_FACE_EXT = VK_DYNAMIC_STATE_FRONT_FACE_EXT,
        E_PRIMITIVE_TOPOLOGY_EXT = VK_DYNAMIC_STATE_PRIMITIVE_TOPOLOGY_EXT,
        E_VIEWPORT_WITH_COUNT_EXT = VK_DYNAMIC_STATE_VIEWPORT_WITH_COUNT_EXT,
        E_SCISSOR_WITH_COUNT_EXT = VK_DYNAMIC_STATE_SCISSOR_WITH_COUNT_EXT,
        E_VERTEX_INPUT_BINDING_STRIDE_EXT = VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE_EXT,
        E_DEPTH_TEST_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_TEST_ENABLE_EXT,
        E_DEPTH_WRITE_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_WRITE_ENABLE_EXT,
        E_DEPTH_COMPARE_OP_EXT = VK_DYNAMIC_STATE_DEPTH_COMPARE_OP_EXT,
        E_DEPTH_BOUNDS_TEST_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_BOUNDS_TEST_ENABLE_EXT,
        E_STENCIL_TEST_ENABLE_EXT = VK_DYNAMIC_STATE_STENCIL_TEST_ENABLE_EXT,
        E_STENCIL_OP_EXT = VK_DYNAMIC_STATE_STENCIL_OP_EXT,
        E_RASTERIZER_DISCARD_ENABLE_EXT = VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE_EXT,
        E_DEPTH_BIAS_ENABLE_EXT = VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE_EXT,
        E_PRIMITIVE_RESTART_ENABLE_EXT = VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE_EXT,
    };

    // VkFrontFace
    enum class EFrontFace : uint32 {
        E_COUNTER_CLOCKWISE = VK_FRONT_FACE_COUNTER_CLOCKWISE,
        E_CLOCKWISE = VK_FRONT_FACE_CLOCKWISE,
    };

    // VkPolygonMode
    enum class EPolygonMode : uint32 {
        E_FILL = VK_POLYGON_MODE_FILL,
        E_LINE = VK_POLYGON_MODE_LINE,
        E_POINT = VK_POLYGON_MODE_POINT,
        E_FILL_RECTANGLE_NV = VK_POLYGON_MODE_FILL_RECTANGLE_NV,
    };

    // VkStencilOp
    enum class EStencilOperator : uint32 {
        E_KEEP = VK_STENCIL_OP_KEEP,
        E_ZERO = VK_STENCIL_OP_ZERO,
        E_REPLACE = VK_STENCIL_OP_REPLACE,
        E_INCREMENT_AND_CLAMP = VK_STENCIL_OP_INCREMENT_AND_CLAMP,
        E_DECREMENT_AND_CLAMP = VK_STENCIL_OP_DECREMENT_AND_CLAMP,
        E_INVERT = VK_STENCIL_OP_INVERT,
        E_INCREMENT_AND_WRAP = VK_STENCIL_OP_INCREMENT_AND_WRAP,
        E_DECREMENT_AND_WRAP = VK_STENCIL_OP_DECREMENT_AND_WRAP,
    };

    // VkLogicOp
    enum class ELogicOperator : uint32 {
        E_CLEAR = VK_LOGIC_OP_CLEAR,
        E_AND = VK_LOGIC_OP_AND,
        E_AND_REVERSE = VK_LOGIC_OP_AND_REVERSE,
        E_COPY = VK_LOGIC_OP_COPY,
        E_AND_INVERTED = VK_LOGIC_OP_AND_INVERTED,
        E_NO_OP = VK_LOGIC_OP_NO_OP,
        E_XOR = VK_LOGIC_OP_XOR,
        E_OR = VK_LOGIC_OP_OR,
        E_NOR = VK_LOGIC_OP_NOR,
        E_EQUIVALENT = VK_LOGIC_OP_EQUIVALENT,
        E_INVERT = VK_LOGIC_OP_INVERT,
        E_OR_REVERSE = VK_LOGIC_OP_OR_REVERSE,
        E_COPY_INVERTED = VK_LOGIC_OP_COPY_INVERTED,
        E_OR_INVERTED = VK_LOGIC_OP_OR_INVERTED,
        E_NAND = VK_LOGIC_OP_NAND,
        E_SET = VK_LOGIC_OP_SET,
    };

    // VkBorderColor
    enum class ESamplerBorderColor : uint32 {
        E_FLOAT_TRANSPARENT_BLACK = VK_BORDER_COLOR_FLOAT_TRANSPARENT_BLACK,
        E_INT_TRANSPARENT_BLACK = VK_BORDER_COLOR_INT_TRANSPARENT_BLACK,
        E_FLOAT_OPAQUE_BLACK = VK_BORDER_COLOR_FLOAT_OPAQUE_BLACK,
        E_INT_OPAQUE_BLACK = VK_BORDER_COLOR_INT_OPAQUE_BLACK,
        E_FLOAT_OPAQUE_WHITE = VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE,
        E_INT_OPAQUE_WHITE = VK_BORDER_COLOR_INT_OPAQUE_WHITE,
        E_FLOAT_CUSTOM_EXT = VK_BORDER_COLOR_FLOAT_CUSTOM_EXT,
        E_INT_CUSTOM_EXT = VK_BORDER_COLOR_INT_CUSTOM_EXT,
    };

    // VkFilter
    enum class ESamplerFilter : uint32 {
        E_NEAREST = VK_FILTER_NEAREST,
        E_LINEAR = VK_FILTER_LINEAR,
        E_CUBIC_IMG = VK_FILTER_CUBIC_IMG,
        E_CUBIC_EXT = VK_FILTER_CUBIC_EXT,
    };

    // VkSamplerAddressMode
    enum class ESamplerAddressMode : uint32 {
        E_REPEAT = VK_SAMPLER_ADDRESS_MODE_REPEAT,
        E_MIRRORED_REPEAT = VK_SAMPLER_ADDRESS_MODE_MIRRORED_REPEAT,
        E_CLAMP_TO_EDGE = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
        E_CLAMP_TO_BORDER = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER,
        E_MIRROR_CLAMP_TO_EDGE = VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE,
        E_MIRROR_CLAMP_TO_EDGE_KHR = VK_SAMPLER_ADDRESS_MODE_MIRROR_CLAMP_TO_EDGE_KHR,
    };

    // VkSamplerMipmapMode
    enum class ESamplerMipmapMode : uint32 {
        E_NEAREST = VK_SAMPLER_MIPMAP_MODE_NEAREST,
        E_LINEAR = VK_SAMPLER_MIPMAP_MODE_LINEAR,
    };

    // VkDescriptorType
    enum class EDescriptorType : uint32 {
        E_SAMPLER = VK_DESCRIPTOR_TYPE_SAMPLER,
        E_COMBINED_IMAGE_SAMPLER = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
        E_SAMPLED_IMAGE = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
        E_STORAGE_IMAGE = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
        E_UNIFORM_TEXEL_BUFFER = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
        E_STORAGE_TEXEL_BUFFER = VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
        E_UNIFORM_BUFFER = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
        E_STORAGE_BUFFER = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
        E_UNIFORM_BUFFER_DYNAMIC = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
        E_STORAGE_BUFFER_DYNAMIC = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC,
        E_INPUT_ATTACHMENT = VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT,
        E_INLINE_UNIFORM_BLOCK = VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK,
        E_ACCELERATION_STRUCTURE_KHR = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR,
        E_ACCELERATION_STRUCTURE_NV = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV,
        E_SAMPLE_WEIGHT_IMAGE_QCOM = VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM,
        E_BLOCK_MATCH_IMAGE_QCOM = VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM,
        E_MUTABLE_EXT = VK_DESCRIPTOR_TYPE_MUTABLE_EXT,
        E_INLINE_UNIFORM_BLOCK_EXT = VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK_EXT,
        E_MUTABLE_VALVE = VK_DESCRIPTOR_TYPE_MUTABLE_VALVE,
    };

    // VkAttachmentLoadOp
    enum class EAttachmentLoadOperator : uint32 {
        E_LOAD = VK_ATTACHMENT_LOAD_OP_LOAD,
        E_CLEAR = VK_ATTACHMENT_LOAD_OP_CLEAR,
        E_DONT_CARE = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        E_NONE_EXT = VK_ATTACHMENT_LOAD_OP_NONE_EXT,
    };

    // VkAttachmentStoreOp
    enum class EAttachmentStoreOperator : uint32 {
        E_STORE = VK_ATTACHMENT_STORE_OP_STORE,
        E_DONT_CARE = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        E_NONE = VK_ATTACHMENT_STORE_OP_NONE,
        E_NONE_KHR = VK_ATTACHMENT_STORE_OP_NONE_KHR,
        E_NONE_QCOM = VK_ATTACHMENT_STORE_OP_NONE_QCOM,
        E_NONE_EXT = VK_ATTACHMENT_STORE_OP_NONE_EXT,
    };
    
    // VkImageAspectFlagBits
    enum class EImageAspect : uint32 {
        E_COLOR = VK_IMAGE_ASPECT_COLOR_BIT,
        E_DEPTH = VK_IMAGE_ASPECT_DEPTH_BIT,
        E_STENCIL = VK_IMAGE_ASPECT_STENCIL_BIT,
        E_METADATA = VK_IMAGE_ASPECT_METADATA_BIT,
        E_PLANE_0 = VK_IMAGE_ASPECT_PLANE_0_BIT,
        E_PLANE_1 = VK_IMAGE_ASPECT_PLANE_1_BIT,
        E_PLANE_2 = VK_IMAGE_ASPECT_PLANE_2_BIT,
        E_NONE = VK_IMAGE_ASPECT_NONE,
        E_MEMORY_PLANE_0_EXT = VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT,
        E_MEMORY_PLANE_1_EXT = VK_IMAGE_ASPECT_MEMORY_PLANE_1_BIT_EXT,
        E_MEMORY_PLANE_2_EXT = VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT,
        E_MEMORY_PLANE_3_EXT = VK_IMAGE_ASPECT_MEMORY_PLANE_3_BIT_EXT,
        E_PLANE_0_KHR = VK_IMAGE_ASPECT_PLANE_0_BIT_KHR,
        E_PLANE_1_KHR = VK_IMAGE_ASPECT_PLANE_1_BIT_KHR,
        E_PLANE_2_KHR = VK_IMAGE_ASPECT_PLANE_2_BIT_KHR,
        E_NONE_KHR = VK_IMAGE_ASPECT_NONE_KHR,
    };

    // VkImageCreateFlagBits
    enum class EImageCreateFlag : uint32 {
        E_SPARSE_BINDING = VK_IMAGE_CREATE_SPARSE_BINDING_BIT,
        E_SPARSE_RESIDENCY = VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT,
        E_SPARSE_ALIASED = VK_IMAGE_CREATE_SPARSE_ALIASED_BIT,
        E_MUTABLE_FORMAT = VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT,
        E_CUBE_COMPATIBLE = VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT,
        E_ALIAS = VK_IMAGE_CREATE_ALIAS_BIT,
        E_SPLIT_INSTANCE_BIND_REGIONS = VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT,
        E_2D_ARRAY_COMPATIBLE = VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT,
        E_BLOCK_TEXEL_VIEW_COMPATIBLE = VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT,
        E_EXTENDED_USAGE = VK_IMAGE_CREATE_EXTENDED_USAGE_BIT,
        E_PROTECTED = VK_IMAGE_CREATE_PROTECTED_BIT,
        E_DISJOINT = VK_IMAGE_CREATE_DISJOINT_BIT,
        E_CORNER_SAMPLED_NV = VK_IMAGE_CREATE_CORNER_SAMPLED_BIT_NV,
        E_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_EXT = VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT,
        E_SUBSAMPLED_EXT = VK_IMAGE_CREATE_SUBSAMPLED_BIT_EXT,
        E_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_EXT = VK_IMAGE_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT,
        E_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_EXT = VK_IMAGE_CREATE_MULTISAMPLED_RENDER_TO_SINGLE_SAMPLED_BIT_EXT,
        E_2D_VIEW_COMPATIBLE_EXT = VK_IMAGE_CREATE_2D_VIEW_COMPATIBLE_BIT_EXT,
        E_FRAGMENT_DENSITY_MAP_OFFSET_QCOM = VK_IMAGE_CREATE_FRAGMENT_DENSITY_MAP_OFFSET_BIT_QCOM,
        E_SPLIT_INSTANCE_BIND_REGIONS_KHR = VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR,
        E_2D_ARRAY_COMPATIBLE_KHR = VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR,
        E_BLOCK_TEXEL_VIEW_COMPATIBLE_KHR = VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR,
        E_EXTENDED_USAGE_KHR = VK_IMAGE_CREATE_EXTENDED_USAGE_BIT_KHR,
        E_DISJOINT_KHR = VK_IMAGE_CREATE_DISJOINT_BIT_KHR,
        E_ALIAS_KHR = VK_IMAGE_CREATE_ALIAS_BIT_KHR,
    };

    // VkSampleCountFlagBits
    enum class ESampleCount : uint32 {
        E_1 = VK_SAMPLE_COUNT_1_BIT,
        E_2 = VK_SAMPLE_COUNT_2_BIT,
        E_4 = VK_SAMPLE_COUNT_4_BIT,
        E_8 = VK_SAMPLE_COUNT_8_BIT,
        E_16 = VK_SAMPLE_COUNT_16_BIT,
        E_32 = VK_SAMPLE_COUNT_32_BIT,
        E_64 = VK_SAMPLE_COUNT_64_BIT,
    };

    // VkImageUsageFlagBits
    enum class EImageUsage : uint32 {
        E_TRANSFER_SRC = VK_IMAGE_USAGE_TRANSFER_SRC_BIT,
        E_TRANSFER_DST = VK_IMAGE_USAGE_TRANSFER_DST_BIT,
        E_SAMPLED = VK_IMAGE_USAGE_SAMPLED_BIT,
        E_STORAGE = VK_IMAGE_USAGE_STORAGE_BIT,
        E_COLOR_ATTACHMENT = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
        E_DEPTH_STENCIL_ATTACHMENT = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
        E_TRANSIENT_ATTACHMENT = VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT,
        E_INPUT_ATTACHMENT = VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT,
        E_VIDEO_DECODE_DST_KHR = VK_IMAGE_USAGE_VIDEO_DECODE_DST_BIT_KHR,
        E_VIDEO_DECODE_SRC_KHR = VK_IMAGE_USAGE_VIDEO_DECODE_SRC_BIT_KHR,
        E_VIDEO_DECODE_DPB_KHR = VK_IMAGE_USAGE_VIDEO_DECODE_DPB_BIT_KHR,
        E_FRAGMENT_DENSITY_MAP_EXT = VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT,
        E_FRAGMENT_SHADING_RATE_ATTACHMENT_KHR = VK_IMAGE_USAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,
        E_ATTACHMENT_FEEDBACK_LOOP_EXT = VK_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT,
        E_INVOCATION_MASK_HUAWEI = VK_IMAGE_USAGE_INVOCATION_MASK_BIT_HUAWEI,
        E_SAMPLE_WEIGHT_QCOM = VK_IMAGE_USAGE_SAMPLE_WEIGHT_BIT_QCOM,
        E_SAMPLE_BLOCK_MATCH_QCOM = VK_IMAGE_USAGE_SAMPLE_BLOCK_MATCH_BIT_QCOM,
        E_SHADING_RATE_IMAGE_NV = VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV,
    };

    // VkMemoryPropertyFlagBits
    enum class EMemoryProperty : uint32 {
        E_DEVICE_LOCAL = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
        E_HOST_VISIBLE = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT,
        E_HOST_COHERENT = VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
        E_HOST_CACHED = VK_MEMORY_PROPERTY_HOST_CACHED_BIT,
        E_LAZILY_ALLOCATED = VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT,
        E_PROTECTED = VK_MEMORY_PROPERTY_PROTECTED_BIT,
        E_DEVICE_COHERENT_AMD = VK_MEMORY_PROPERTY_DEVICE_COHERENT_BIT_AMD,
        E_DEVICE_UNCACHED_AMD = VK_MEMORY_PROPERTY_DEVICE_UNCACHED_BIT_AMD,
        E_RDMA_CAPABLE_NV = VK_MEMORY_PROPERTY_RDMA_CAPABLE_BIT_NV,

        // Extra Flags
        E_DEVICE_MAPPABLE = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT |
                            VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                            VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
        E_HOST_ONLY_COHERENT = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                               VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
        E_HOST_ONLY_CACHED = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                             VK_MEMORY_PROPERTY_HOST_CACHED_BIT,
    };

    // VkQueryPipelineStatisticFlagBits
    enum class EQueryPipelineStatistic : uint32 {
        E_INPUT_ASSEMBLY_VERTICES = VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT,
        E_INPUT_ASSEMBLY_PRIMITIVES = VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT,
        E_VERTEX_SHADER_INVOCATIONS = VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT,
        E_GEOMETRY_SHADER_INVOCATIONS = VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT,
        E_GEOMETRY_SHADER_PRIMITIVES = VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT,
        E_CLIPPING_INVOCATIONS = VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT,
        E_CLIPPING_PRIMITIVES = VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT,
        E_FRAGMENT_SHADER_INVOCATIONS = VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT,
        E_TESSELLATION_CONTROL_SHADER_PATCHES = VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT,
        E_TESSELLATION_EVALUATION_SHADER_INVOCATIONS = VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT,
        E_COMPUTE_SHADER_INVOCATIONS = VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT,
        E_TASK_SHADER_INVOCATIONS_EXT = VK_QUERY_PIPELINE_STATISTIC_TASK_SHADER_INVOCATIONS_BIT_EXT,
        E_MESH_SHADER_INVOCATIONS_EXT = VK_QUERY_PIPELINE_STATISTIC_MESH_SHADER_INVOCATIONS_BIT_EXT,
        E_CLUSTER_CULLING_SHADER_INVOCATIONS_HUAWEI = VK_QUERY_PIPELINE_STATISTIC_CLUSTER_CULLING_SHADER_INVOCATIONS_BIT_HUAWEI,
    };

    // VkQueryResultFlagBits
    enum class EQueryResultFlag : uint32 {
        E_64_BIT = VK_QUERY_RESULT_64_BIT,
        E_WAIT = VK_QUERY_RESULT_WAIT_BIT,
        E_WITH_AVAILABILITY = VK_QUERY_RESULT_WITH_AVAILABILITY_BIT,
        E_PARTIAL = VK_QUERY_RESULT_PARTIAL_BIT,
        E_WITH_STATUS_KHR = VK_QUERY_RESULT_WITH_STATUS_BIT_KHR,
    };

    // VkBufferCreateFlagBits
    enum class EBufferCreateFlag : uint32 {
        E_SPARSE_BINDING = VK_BUFFER_CREATE_SPARSE_BINDING_BIT,
        E_SPARSE_RESIDENCY = VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT,
        E_SPARSE_ALIASED = VK_BUFFER_CREATE_SPARSE_ALIASED_BIT,
        E_PROTECTED = VK_BUFFER_CREATE_PROTECTED_BIT,
        E_DEVICE_ADDRESS_CAPTURE_REPLAY = VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT,
        E_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_EXT = VK_BUFFER_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT,
        E_DEVICE_ADDRESS_CAPTURE_REPLAY_EXT = VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT,
        E_DEVICE_ADDRESS_CAPTURE_REPLAY_KHR = VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_KHR,
    };

    // VkColorComponentFlagBits
    enum class EColorComponent : uint32 {
        E_R = VK_COLOR_COMPONENT_R_BIT,
        E_G = VK_COLOR_COMPONENT_G_BIT,
        E_B = VK_COLOR_COMPONENT_B_BIT,
        E_A = VK_COLOR_COMPONENT_A_BIT,
    };

    // VkShaderStageFlagBits
    enum class EShaderStage : uint32 {
        E_VERTEX = VK_SHADER_STAGE_VERTEX_BIT,
        E_TESSELLATION_CONTROL = VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT,
        E_TESSELLATION_EVALUATION = VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT,
        E_GEOMETRY = VK_SHADER_STAGE_GEOMETRY_BIT,
        E_FRAGMENT = VK_SHADER_STAGE_FRAGMENT_BIT,
        E_COMPUTE = VK_SHADER_STAGE_COMPUTE_BIT,
        E_ALL_GRAPHICS = VK_SHADER_STAGE_ALL_GRAPHICS,
        E_ALL = VK_SHADER_STAGE_ALL,
        E_RAYGEN_KHR = VK_SHADER_STAGE_RAYGEN_BIT_KHR,
        E_ANY_HIT_KHR = VK_SHADER_STAGE_ANY_HIT_BIT_KHR,
        E_CLOSEST_HIT_KHR = VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR,
        E_MISS_KHR = VK_SHADER_STAGE_MISS_BIT_KHR,
        E_INTERSECTION_KHR = VK_SHADER_STAGE_INTERSECTION_BIT_KHR,
        E_CALLABLE_KHR = VK_SHADER_STAGE_CALLABLE_BIT_KHR,
        E_TASK_EXT = VK_SHADER_STAGE_TASK_BIT_EXT,
        E_MESH_EXT = VK_SHADER_STAGE_MESH_BIT_EXT,
        E_SUBPASS_SHADING_HUAWEI = VK_SHADER_STAGE_SUBPASS_SHADING_BIT_HUAWEI,
        E_CLUSTER_CULLING_HUAWEI = VK_SHADER_STAGE_CLUSTER_CULLING_BIT_HUAWEI,
        E_RAYGEN_NV = VK_SHADER_STAGE_RAYGEN_BIT_NV,
        E_ANY_HIT_NV = VK_SHADER_STAGE_ANY_HIT_BIT_NV,
        E_CLOSEST_HIT_NV = VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV,
        E_MISS_NV = VK_SHADER_STAGE_MISS_BIT_NV,
        E_INTERSECTION_NV = VK_SHADER_STAGE_INTERSECTION_BIT_NV,
        E_CALLABLE_NV = VK_SHADER_STAGE_CALLABLE_BIT_NV,
        E_TASK_NV = VK_SHADER_STAGE_TASK_BIT_NV,
        E_MESH_NV = VK_SHADER_STAGE_MESH_BIT_NV,
    };

    // VkCullModeFlagBits
    enum class ECullMode : uint32 {
        E_NONE = VK_CULL_MODE_NONE,
        E_FRONT = VK_CULL_MODE_FRONT_BIT,
        E_BACK = VK_CULL_MODE_BACK_BIT,
        E_FRONT_AND_BACK = VK_CULL_MODE_FRONT_AND_BACK,
    };

    // VkDescriptorPoolCreateFlagBits
    enum class EDescriptorPoolCreateFlag : uint32 {
        E_FREE_DESCRIPTOR_SET_BIT = VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT,
        E_UPDATE_AFTER_BIND_BIT = VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT,
        E_HOST_ONLY_BIT_EXT = VK_DESCRIPTOR_POOL_CREATE_HOST_ONLY_BIT_EXT,
        E_ALLOW_OVERALLOCATION_SETS_BIT_NV = VK_DESCRIPTOR_POOL_CREATE_ALLOW_OVERALLOCATION_SETS_BIT_NV,
        E_ALLOW_OVERALLOCATION_POOLS_BIT_NV = VK_DESCRIPTOR_POOL_CREATE_ALLOW_OVERALLOCATION_POOLS_BIT_NV,
        E_UPDATE_AFTER_BIND_BIT_EXT = VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT_EXT,
        E_HOST_ONLY_BIT_VALVE = VK_DESCRIPTOR_POOL_CREATE_HOST_ONLY_BIT_VALVE,
    };
    
    // VkDescriptorSetLayoutCreateFlagBits
    enum class EDescriptorLayoutCreateFlag : uint32 {
        E_UPDATE_AFTER_BIND_POOL = VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT,
        E_PUSH_DESCRIPTOR_KHR = VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR,
        E_DESCRIPTOR_BUFFER_EXT = VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT,
        E_EMBEDDED_IMMUTABLE_SAMPLERS_EXT = VK_DESCRIPTOR_SET_LAYOUT_CREATE_EMBEDDED_IMMUTABLE_SAMPLERS_BIT_EXT,
        E_INDIRECT_BINDABLE_NV = VK_DESCRIPTOR_SET_LAYOUT_CREATE_INDIRECT_BINDABLE_BIT_NV,
        E_HOST_ONLY_POOL_EXT = VK_DESCRIPTOR_SET_LAYOUT_CREATE_HOST_ONLY_POOL_BIT_EXT,
        E_UPDATE_AFTER_BIND_POOL_EXT = VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT,
        E_HOST_ONLY_POOL_VALVE = VK_DESCRIPTOR_SET_LAYOUT_CREATE_HOST_ONLY_POOL_BIT_VALVE,
    };

    // VkCommandPoolCreateFlagBits
    enum class ECommandPoolCreateFlag : uint32 {
        E_TRANSIENT = VK_COMMAND_POOL_CREATE_TRANSIENT_BIT,
        E_RESET_COMMAND_BUFFER = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,
        E_PROTECTED = VK_COMMAND_POOL_CREATE_PROTECTED_BIT,
    };

    // VkSamplerReductionMode
    enum class ESamplerReductionMode : uint32 {
        E_WEIGHTED_AVERAGE = VK_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE,
        E_MIN = VK_SAMPLER_REDUCTION_MODE_MIN,
        E_MAX = VK_SAMPLER_REDUCTION_MODE_MAX,
        E_WEIGHTED_AVERAGE_RANGECLAMP_QCOM = VK_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE_RANGECLAMP_QCOM,
        E_WEIGHTED_AVERAGE_EXT = VK_SAMPLER_REDUCTION_MODE_WEIGHTED_AVERAGE_EXT,
        E_MIN_EXT = VK_SAMPLER_REDUCTION_MODE_MIN_EXT,
        E_MAX_EXT = VK_SAMPLER_REDUCTION_MODE_MAX_EXT,
    };
    
    // VkDescriptorBindingFlagBits
    enum class EDescriptorBindingFlag : uint32 {
        E_UPDATE_AFTER_BIND = VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT,
        E_UPDATE_UNUSED_WHILE_PENDING = VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT,
        E_PARTIALLY_BOUND = VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT,
        E_VARIABLE_DESCRIPTOR_COUNT = VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT,
        E_UPDATE_AFTER_BIND_EXT = VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT,
        E_UPDATE_UNUSED_WHILE_PENDING_EXT = VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT,
        E_PARTIALLY_BOUND_EXT = VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT,
        E_VARIABLE_DESCRIPTOR_COUNT_EXT = VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT,
    };
    
    // VkPipelineStageFlagBits2
    enum class EPipelineStage : uint64 {
        E_NONE = VK_PIPELINE_STAGE_2_NONE,
        E_NONE_KHR = VK_PIPELINE_STAGE_2_NONE_KHR,
        E_TOP_OF_PIPE = VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT,
        E_TOP_OF_PIPE_KHR = VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT_KHR,
        E_DRAW_INDIRECT = VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT,
        E_DRAW_INDIRECT_KHR = VK_PIPELINE_STAGE_2_DRAW_INDIRECT_BIT_KHR,
        E_VERTEX_INPUT = VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT,
        E_VERTEX_INPUT_KHR = VK_PIPELINE_STAGE_2_VERTEX_INPUT_BIT_KHR,
        E_VERTEX_SHADER = VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT,
        E_VERTEX_SHADER_KHR = VK_PIPELINE_STAGE_2_VERTEX_SHADER_BIT_KHR,
        E_TESSELLATION_CONTROL_SHADER = VK_PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT,
        E_TESSELLATION_CONTROL_SHADER_KHR = VK_PIPELINE_STAGE_2_TESSELLATION_CONTROL_SHADER_BIT_KHR,
        E_TESSELLATION_EVALUATION_SHADER = VK_PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT,
        E_TESSELLATION_EVALUATION_SHADER_KHR = VK_PIPELINE_STAGE_2_TESSELLATION_EVALUATION_SHADER_BIT_KHR,
        E_GEOMETRY_SHADER = VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT,
        E_GEOMETRY_SHADER_KHR = VK_PIPELINE_STAGE_2_GEOMETRY_SHADER_BIT_KHR,
        E_FRAGMENT_SHADER = VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT,
        E_FRAGMENT_SHADER_KHR = VK_PIPELINE_STAGE_2_FRAGMENT_SHADER_BIT_KHR,
        E_EARLY_FRAGMENT_TESTS = VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT,
        E_EARLY_FRAGMENT_TESTS_KHR = VK_PIPELINE_STAGE_2_EARLY_FRAGMENT_TESTS_BIT_KHR,
        E_LATE_FRAGMENT_TESTS = VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT,
        E_LATE_FRAGMENT_TESTS_KHR = VK_PIPELINE_STAGE_2_LATE_FRAGMENT_TESTS_BIT_KHR,
        E_COLOR_ATTACHMENT_OUTPUT = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
        E_COLOR_ATTACHMENT_OUTPUT_KHR = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT_KHR,
        E_COMPUTE_SHADER = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
        E_COMPUTE_SHADER_KHR = VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT_KHR,
        E_ALL_TRANSFER = VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT,
        E_ALL_TRANSFER_KHR = VK_PIPELINE_STAGE_2_ALL_TRANSFER_BIT_KHR,
        E_TRANSFER = VK_PIPELINE_STAGE_2_TRANSFER_BIT,
        E_TRANSFER_KHR = VK_PIPELINE_STAGE_2_TRANSFER_BIT_KHR,
        E_BOTTOM_OF_PIPE = VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT,
        E_BOTTOM_OF_PIPE_KHR = VK_PIPELINE_STAGE_2_BOTTOM_OF_PIPE_BIT_KHR,
        E_HOST = VK_PIPELINE_STAGE_2_HOST_BIT,
        E_HOST_KHR = VK_PIPELINE_STAGE_2_HOST_BIT_KHR,
        E_ALL_GRAPHICS = VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT,
        E_ALL_GRAPHICS_KHR = VK_PIPELINE_STAGE_2_ALL_GRAPHICS_BIT_KHR,
        E_ALL_COMMANDS = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT,
        E_ALL_COMMANDS_KHR = VK_PIPELINE_STAGE_2_ALL_COMMANDS_BIT_KHR,
        E_COPY = VK_PIPELINE_STAGE_2_COPY_BIT,
        E_COPY_KHR = VK_PIPELINE_STAGE_2_COPY_BIT_KHR,
        E_RESOLVE = VK_PIPELINE_STAGE_2_RESOLVE_BIT,
        E_RESOLVE_KHR = VK_PIPELINE_STAGE_2_RESOLVE_BIT_KHR,
        E_BLIT = VK_PIPELINE_STAGE_2_BLIT_BIT,
        E_BLIT_KHR = VK_PIPELINE_STAGE_2_BLIT_BIT_KHR,
        E_CLEAR = VK_PIPELINE_STAGE_2_CLEAR_BIT,
        E_CLEAR_KHR = VK_PIPELINE_STAGE_2_CLEAR_BIT_KHR,
        E_INDEX_INPUT = VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT,
        E_INDEX_INPUT_KHR = VK_PIPELINE_STAGE_2_INDEX_INPUT_BIT_KHR,
        E_VERTEX_ATTRIBUTE_INPUT = VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT,
        E_VERTEX_ATTRIBUTE_INPUT_KHR = VK_PIPELINE_STAGE_2_VERTEX_ATTRIBUTE_INPUT_BIT_KHR,
        E_PRE_RASTERIZATION_SHADERS = VK_PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT,
        E_PRE_RASTERIZATION_SHADERS_KHR = VK_PIPELINE_STAGE_2_PRE_RASTERIZATION_SHADERS_BIT_KHR,
        E_VIDEO_DECODE_KHR = VK_PIPELINE_STAGE_2_VIDEO_DECODE_BIT_KHR,
        E_TRANSFORM_FEEDBACK_EXT = VK_PIPELINE_STAGE_2_TRANSFORM_FEEDBACK_BIT_EXT,
        E_CONDITIONAL_RENDERING_EXT = VK_PIPELINE_STAGE_2_CONDITIONAL_RENDERING_BIT_EXT,
        E_COMMAND_PREPROCESS_NV = VK_PIPELINE_STAGE_2_COMMAND_PREPROCESS_BIT_NV,
        E_FRAGMENT_SHADING_RATE_ATTACHMENT_KHR = VK_PIPELINE_STAGE_2_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,
        E_SHADING_RATE_IMAGE_NV = VK_PIPELINE_STAGE_2_SHADING_RATE_IMAGE_BIT_NV,
        E_ACCELERATION_STRUCTURE_BUILD_KHR = VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
        E_RAY_TRACING_SHADER_KHR = VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_KHR,
        E_RAY_TRACING_SHADER_NV = VK_PIPELINE_STAGE_2_RAY_TRACING_SHADER_BIT_NV,
        E_ACCELERATION_STRUCTURE_BUILD_NV = VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_BUILD_BIT_NV,
        E_FRAGMENT_DENSITY_PROCESS_EXT = VK_PIPELINE_STAGE_2_FRAGMENT_DENSITY_PROCESS_BIT_EXT,
        E_TASK_SHADER_NV = VK_PIPELINE_STAGE_2_TASK_SHADER_BIT_NV,
        E_MESH_SHADER_NV = VK_PIPELINE_STAGE_2_MESH_SHADER_BIT_NV,
        E_TASK_SHADER_EXT = VK_PIPELINE_STAGE_2_TASK_SHADER_BIT_EXT,
        E_MESH_SHADER_EXT = VK_PIPELINE_STAGE_2_MESH_SHADER_BIT_EXT,
        E_SUBPASS_SHADING_HUAWEI = VK_PIPELINE_STAGE_2_SUBPASS_SHADING_BIT_HUAWEI,
        E_INVOCATION_MASK_HUAWEI = VK_PIPELINE_STAGE_2_INVOCATION_MASK_BIT_HUAWEI,
        E_ACCELERATION_STRUCTURE_COPY_KHR = VK_PIPELINE_STAGE_2_ACCELERATION_STRUCTURE_COPY_BIT_KHR,
        E_MICROMAP_BUILD_EXT = VK_PIPELINE_STAGE_2_MICROMAP_BUILD_BIT_EXT,
        E_CLUSTER_CULLING_SHADER_HUAWEI = VK_PIPELINE_STAGE_2_CLUSTER_CULLING_SHADER_BIT_HUAWEI,
        E_OPTICAL_FLOW_NV = VK_PIPELINE_STAGE_2_OPTICAL_FLOW_BIT_NV,
    };
    
    // VkAccessFlagBits2
    enum class EResourceAccess : uint64 {
        E_NONE = VK_ACCESS_2_NONE,
        E_NONE_KHR = VK_ACCESS_2_NONE_KHR,
        E_INDIRECT_COMMAND_READ = VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT,
        E_INDIRECT_COMMAND_READ_KHR = VK_ACCESS_2_INDIRECT_COMMAND_READ_BIT_KHR,
        E_INDEX_READ = VK_ACCESS_2_INDEX_READ_BIT,
        E_INDEX_READ_KHR = VK_ACCESS_2_INDEX_READ_BIT_KHR,
        E_VERTEX_ATTRIBUTE_READ = VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT,
        E_VERTEX_ATTRIBUTE_READ_KHR = VK_ACCESS_2_VERTEX_ATTRIBUTE_READ_BIT_KHR,
        E_UNIFORM_READ = VK_ACCESS_2_UNIFORM_READ_BIT,
        E_UNIFORM_READ_KHR = VK_ACCESS_2_UNIFORM_READ_BIT_KHR,
        E_INPUT_ATTACHMENT_READ = VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT,
        E_INPUT_ATTACHMENT_READ_KHR = VK_ACCESS_2_INPUT_ATTACHMENT_READ_BIT_KHR,
        E_SHADER_READ = VK_ACCESS_2_SHADER_READ_BIT,
        E_SHADER_READ_KHR = VK_ACCESS_2_SHADER_READ_BIT_KHR,
        E_SHADER_WRITE = VK_ACCESS_2_SHADER_WRITE_BIT,
        E_SHADER_WRITE_KHR = VK_ACCESS_2_SHADER_WRITE_BIT_KHR,
        E_COLOR_ATTACHMENT_READ = VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT,
        E_COLOR_ATTACHMENT_READ_KHR = VK_ACCESS_2_COLOR_ATTACHMENT_READ_BIT_KHR,
        E_COLOR_ATTACHMENT_WRITE = VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT,
        E_COLOR_ATTACHMENT_WRITE_KHR = VK_ACCESS_2_COLOR_ATTACHMENT_WRITE_BIT_KHR,
        E_DEPTH_STENCIL_ATTACHMENT_READ = VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT,
        E_DEPTH_STENCIL_ATTACHMENT_READ_KHR = VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_READ_BIT_KHR,
        E_DEPTH_STENCIL_ATTACHMENT_WRITE = VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT,
        E_DEPTH_STENCIL_ATTACHMENT_WRITE_KHR = VK_ACCESS_2_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT_KHR,
        E_TRANSFER_READ = VK_ACCESS_2_TRANSFER_READ_BIT,
        E_TRANSFER_READ_KHR = VK_ACCESS_2_TRANSFER_READ_BIT_KHR,
        E_TRANSFER_WRITE = VK_ACCESS_2_TRANSFER_WRITE_BIT,
        E_TRANSFER_WRITE_KHR = VK_ACCESS_2_TRANSFER_WRITE_BIT_KHR,
        E_HOST_READ = VK_ACCESS_2_HOST_READ_BIT,
        E_HOST_READ_KHR = VK_ACCESS_2_HOST_READ_BIT_KHR,
        E_HOST_WRITE = VK_ACCESS_2_HOST_WRITE_BIT,
        E_HOST_WRITE_KHR = VK_ACCESS_2_HOST_WRITE_BIT_KHR,
        E_MEMORY_READ = VK_ACCESS_2_MEMORY_READ_BIT,
        E_MEMORY_READ_KHR = VK_ACCESS_2_MEMORY_READ_BIT_KHR,
        E_MEMORY_WRITE = VK_ACCESS_2_MEMORY_WRITE_BIT,
        E_MEMORY_WRITE_KHR = VK_ACCESS_2_MEMORY_WRITE_BIT_KHR,
        E_SHADER_SAMPLED_READ = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT,
        E_SHADER_SAMPLED_READ_KHR = VK_ACCESS_2_SHADER_SAMPLED_READ_BIT_KHR,
        E_SHADER_STORAGE_READ = VK_ACCESS_2_SHADER_STORAGE_READ_BIT,
        E_SHADER_STORAGE_READ_KHR = VK_ACCESS_2_SHADER_STORAGE_READ_BIT_KHR,
        E_SHADER_STORAGE_WRITE = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
        E_SHADER_STORAGE_WRITE_KHR = VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT_KHR,
        E_VIDEO_DECODE_READ_KHR = VK_ACCESS_2_VIDEO_DECODE_READ_BIT_KHR,
        E_VIDEO_DECODE_WRITE_KHR = VK_ACCESS_2_VIDEO_DECODE_WRITE_BIT_KHR,
        E_TRANSFORM_FEEDBACK_WRITE_EXT = VK_ACCESS_2_TRANSFORM_FEEDBACK_WRITE_BIT_EXT,
        E_TRANSFORM_FEEDBACK_COUNTER_READ_EXT = VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT,
        E_TRANSFORM_FEEDBACK_COUNTER_WRITE_EXT = VK_ACCESS_2_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT,
        E_CONDITIONAL_RENDERING_READ_EXT = VK_ACCESS_2_CONDITIONAL_RENDERING_READ_BIT_EXT,
        E_COMMAND_PREPROCESS_READ_NV = VK_ACCESS_2_COMMAND_PREPROCESS_READ_BIT_NV,
        E_COMMAND_PREPROCESS_WRITE_NV = VK_ACCESS_2_COMMAND_PREPROCESS_WRITE_BIT_NV,
        E_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_KHR = VK_ACCESS_2_FRAGMENT_SHADING_RATE_ATTACHMENT_READ_BIT_KHR,
        E_SHADING_RATE_IMAGE_READ_NV = VK_ACCESS_2_SHADING_RATE_IMAGE_READ_BIT_NV,
        E_ACCELERATION_STRUCTURE_READ_KHR = VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_KHR,
        E_ACCELERATION_STRUCTURE_WRITE_KHR = VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_KHR,
        E_ACCELERATION_STRUCTURE_READ_NV = VK_ACCESS_2_ACCELERATION_STRUCTURE_READ_BIT_NV,
        E_ACCELERATION_STRUCTURE_WRITE_NV = VK_ACCESS_2_ACCELERATION_STRUCTURE_WRITE_BIT_NV,
        E_FRAGMENT_DENSITY_MAP_READ_EXT = VK_ACCESS_2_FRAGMENT_DENSITY_MAP_READ_BIT_EXT,
        E_COLOR_ATTACHMENT_READ_NONCOHERENT_EXT = VK_ACCESS_2_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT,
        E_DESCRIPTOR_BUFFER_READ_EXT = VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT,
        E_INVOCATION_MASK_READ_HUAWEI = VK_ACCESS_2_INVOCATION_MASK_READ_BIT_HUAWEI,
        E_SHADER_BINDING_TABLE_READ_KHR = VK_ACCESS_2_SHADER_BINDING_TABLE_READ_BIT_KHR,
        E_MICROMAP_READ_EXT = VK_ACCESS_2_MICROMAP_READ_BIT_EXT,
        E_MICROMAP_WRITE_EXT = VK_ACCESS_2_MICROMAP_WRITE_BIT_EXT,
        E_OPTICAL_FLOW_READ_NV = VK_ACCESS_2_OPTICAL_FLOW_READ_BIT_NV,
        E_OPTICAL_FLOW_WRITE_NV = VK_ACCESS_2_OPTICAL_FLOW_WRITE_BIT_NV,
    };

    // VkPresentModeKHR
    enum class EPresentMode : uint32 {
        E_IMMEDIATE_KHR = VK_PRESENT_MODE_IMMEDIATE_KHR,
        E_MAILBOX_KHR = VK_PRESENT_MODE_MAILBOX_KHR,
        E_FIFO_KHR = VK_PRESENT_MODE_FIFO_KHR,
        E_FIFO_RELAXED_KHR = VK_PRESENT_MODE_FIFO_RELAXED_KHR,
        E_SHARED_DEMAND_REFRESH_KHR = VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR,
        E_SHARED_CONTINUOUS_REFRESH_KHR = VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR,
    };

    // VkColorSpaceKHR
    enum class EColorSpace : uint32 {
        E_SRGB_NONLINEAR_KHR = VK_COLOR_SPACE_SRGB_NONLINEAR_KHR,
        E_DISPLAY_P3_NONLINEAR_EXT = VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT,
        E_EXTENDED_SRGB_LINEAR_EXT = VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT,
        E_DISPLAY_P3_LINEAR_EXT = VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT,
        E_DCI_P3_NONLINEAR_EXT = VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT,
        E_BT709_LINEAR_EXT = VK_COLOR_SPACE_BT709_LINEAR_EXT,
        E_BT709_NONLINEAR_EXT = VK_COLOR_SPACE_BT709_NONLINEAR_EXT,
        E_BT2020_LINEAR_EXT = VK_COLOR_SPACE_BT2020_LINEAR_EXT,
        E_HDR10_ST2084_EXT = VK_COLOR_SPACE_HDR10_ST2084_EXT,
        E_DOLBYVISION_EXT = VK_COLOR_SPACE_DOLBYVISION_EXT,
        E_HDR10_HLG_EXT = VK_COLOR_SPACE_HDR10_HLG_EXT,
        E_ADOBERGB_LINEAR_EXT = VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT,
        E_ADOBERGB_NONLINEAR_EXT = VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT,
        E_PASS_THROUGH_EXT = VK_COLOR_SPACE_PASS_THROUGH_EXT,
        E_EXTENDED_SRGB_NONLINEAR_EXT = VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT,
        E_DISPLAY_NATIVE_AMD = VK_COLOR_SPACE_DISPLAY_NATIVE_AMD,
        E_DCI_P3_LINEAR_EXT = VK_COLOR_SPACE_DCI_P3_LINEAR_EXT,
    };

    // VkAccelerationStructureTypeKHR
    enum class EAccelerationStructureType : uint32 {
        E_TOP_LEVEL_KHR = VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR,
        E_BOTTOM_LEVEL_KHR = VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR,
        E_GENERIC_KHR = VK_ACCELERATION_STRUCTURE_TYPE_GENERIC_KHR,
        E_TOP_LEVEL_NV = VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_NV,
        E_BOTTOM_LEVEL_NV = VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_NV,
    };
    
    // VkCopyAccelerationStructureModeKHR
    enum class EAccelerationStructureCopyMode : uint32 {
        E_CLONE_KHR = VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHR,
        E_COMPACT_KHR = VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_KHR,
        E_SERIALIZE_KHR = VK_COPY_ACCELERATION_STRUCTURE_MODE_SERIALIZE_KHR,
        E_DESERIALIZE_KHR = VK_COPY_ACCELERATION_STRUCTURE_MODE_DESERIALIZE_KHR,
        E_CLONE_NV = VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_NV,
        E_COMPACT_NV = VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_NV,
    };
    
    // VkGeometryFlagBitsKHR
    enum class EAccelerationStructureGeometryFlag : uint32 {
        E_OPAQUE_KHR = VK_GEOMETRY_OPAQUE_BIT_KHR,
        E_NO_DUPLICATE_ANY_HIT_INVOCATION_KHR = VK_GEOMETRY_NO_DUPLICATE_ANY_HIT_INVOCATION_BIT_KHR,
        E_OPAQUE_NV = VK_GEOMETRY_OPAQUE_BIT_NV,
        E_NO_DUPLICATE_ANY_HIT_INVOCATION_NV = VK_GEOMETRY_NO_DUPLICATE_ANY_HIT_INVOCATION_BIT_NV,
    };
    
    // VkGeometryInstanceFlagBitsKHR
    enum class EAccelerationStructureGeometryInstanceFlag : uint32 {
        E_TRIANGLE_FACING_CULL_DISABLE_KHR = VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR,
        E_TRIANGLE_FLIP_FACING_KHR = VK_GEOMETRY_INSTANCE_TRIANGLE_FLIP_FACING_BIT_KHR,
        E_FORCE_OPAQUE_KHR = VK_GEOMETRY_INSTANCE_FORCE_OPAQUE_BIT_KHR,
        E_FORCE_NO_OPAQUE_KHR = VK_GEOMETRY_INSTANCE_FORCE_NO_OPAQUE_BIT_KHR,
        E_FORCE_OPACITY_MICROMAP_2_STATE_EXT = VK_GEOMETRY_INSTANCE_FORCE_OPACITY_MICROMAP_2_STATE_EXT,
        E_DISABLE_OPACITY_MICROMAPS_EXT = VK_GEOMETRY_INSTANCE_DISABLE_OPACITY_MICROMAPS_EXT,
        E_TRIANGLE_FRONT_COUNTERCLOCKWISE_KHR = VK_GEOMETRY_INSTANCE_TRIANGLE_FRONT_COUNTERCLOCKWISE_BIT_KHR,
        E_TRIANGLE_CULL_DISABLE_NV = VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV,
        E_TRIANGLE_FRONT_COUNTERCLOCKWISE_NV = VK_GEOMETRY_INSTANCE_TRIANGLE_FRONT_COUNTERCLOCKWISE_BIT_NV,
        E_FORCE_OPAQUE_NV = VK_GEOMETRY_INSTANCE_FORCE_OPAQUE_BIT_NV,
        E_FORCE_NO_OPAQUE_NV = VK_GEOMETRY_INSTANCE_FORCE_NO_OPAQUE_BIT_NV,
    };
    
    // VkBuildAccelerationStructureFlagBitsKHR
    enum class EAccelerationStructureBuildFlag : uint32 {
        E_ALLOW_UPDATE_KHR = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR,
        E_ALLOW_COMPACTION_KHR = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_KHR,
        E_PREFER_FAST_TRACE_KHR = VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR,
        E_PREFER_FAST_BUILD_KHR = VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR,
        E_LOW_MEMORY_KHR = VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_KHR,
        E_MOTION_NV = VK_BUILD_ACCELERATION_STRUCTURE_MOTION_BIT_NV,
        E_ALLOW_OPACITY_MICROMAP_UPDATE_EXT = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_UPDATE_EXT,
        E_ALLOW_DISABLE_OPACITY_MICROMAPS_EXT = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_DISABLE_OPACITY_MICROMAPS_EXT,
        E_ALLOW_OPACITY_MICROMAP_DATA_UPDATE_EXT = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_DATA_UPDATE_EXT,
        E_ALLOW_DATA_ACCESS_KHR = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_DATA_ACCESS_KHR,
        E_ALLOW_UPDATE_NV = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV,
        E_ALLOW_COMPACTION_NV = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV,
        E_PREFER_FAST_TRACE_NV = VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV,
        E_PREFER_FAST_BUILD_NV = VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV,
        E_LOW_MEMORY_NV = VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV,
    };

    // VkBuildAccelerationStructureModeKHR
    enum class EAccelerationStructureBuildMode : uint32 {
        E_BUILD_KHR = VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR,
        E_UPDATE_KHR = VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR,
    };

    namespace Constant {
        constexpr static auto EXTERNAL_SUBPASS = VK_SUBPASS_EXTERNAL;
        constexpr static auto LOD_CLAMP_NONE = VK_LOD_CLAMP_NONE;
        constexpr static auto SUBRESOURCE_LEVEL_IGNORED = -1_u32;
        constexpr static auto SUBRESOURCE_LAYER_IGNORED = -1_u32;
        constexpr static auto SUBRESOURCE_REMAINING_LEVELS = VK_REMAINING_MIP_LEVELS;
        constexpr static auto SUBRESOURCE_REMAINING_LAYERS = VK_REMAINING_ARRAY_LAYERS;
        constexpr static auto WHOLE_SIZE = VK_WHOLE_SIZE;
        constexpr static auto ATTACHMENT_UNUSED = VK_ATTACHMENT_UNUSED;
        constexpr static auto QUEUE_FAMILY_IGNORED = VK_QUEUE_FAMILY_IGNORED;
    }

    template <typename T, typename U = std::underlying_type_t<T>, typename = std::enable_if_t<std::is_enum_v<T>>>
    RETINA_NODISCARD constexpr auto operator ~(const T& value) noexcept -> T {
        return static_cast<T>(~static_cast<U>(value));
    }

    template <typename T, typename U = std::underlying_type_t<T>, typename = std::enable_if_t<std::is_enum_v<T>>>
    RETINA_NODISCARD constexpr auto operator |(const T& left, const T& right) noexcept -> T {
        return static_cast<T>(static_cast<U>(left) | static_cast<U>(right));
    }

    template <typename T, typename U = std::underlying_type_t<T>, typename = std::enable_if_t<std::is_enum_v<T>>>
    RETINA_NODISCARD constexpr auto operator &(const T& left, const T& right) noexcept -> T {
        return static_cast<T>(static_cast<U>(left) & static_cast<U>(right));
    }

    template <typename T, typename U = std::underlying_type_t<T>, typename = std::enable_if_t<std::is_enum_v<T>>>
    RETINA_NODISCARD constexpr auto operator ^(const T& left, const T& right) noexcept -> T {
        return static_cast<T>(static_cast<U>(left) ^ static_cast<U>(right));
    }

    template <typename T, typename = std::enable_if_t<std::is_enum_v<T>>>
    constexpr auto operator |=(T& left, const T& right) noexcept -> T& {
        return left = static_cast<T>(left | right);
    }

    template <typename T, typename = std::enable_if_t<std::is_enum_v<T>>>
    constexpr auto operator &=(T& left, const T& right) noexcept -> T& {
        return left = static_cast<T>(left & right);
    }

    template <typename T, typename = std::enable_if_t<std::is_enum_v<T>>>
    constexpr auto operator ^=(T& left, const T& right) noexcept -> T& {
        return left = static_cast<T>(left ^ right);
    }

    template <typename E>
        requires (std::is_enum_v<E>)
    RETINA_NODISCARD constexpr auto IsFlagEnabled(const E& value, const E& flag) noexcept -> bool {
        return (value & flag) == flag;
    }
}
